/* Bruno Electric — Phase 3 calculation engines. */
(function(root){
'use strict';
const R=root.BrunoPhase3Rules;if(!R)throw new Error('BrunoPhase3Rules required');
function num(v,n,zero){if(v===''||v==null)throw new Error((n||'value')+' is required');const x=Number(v);if(!Number.isFinite(x)||(zero?x<0:x<=0))throw new Error((n||'value')+(zero?' must be >= 0':' must be > 0'));return x}
function one(v,a,n){if(a.indexOf(v)<0)throw new Error((n||'value')+' is unsupported');return v}
function standardUp(a){a=num(a,'amps');for(const x of R.standardOcpd)if(x>=a)return x;return null}
function standardExact(a){a=num(a,'OCPD');if(R.standardOcpd.indexOf(a)<0)throw new Error('OCPD must be a supported standard rating');return a}
function egc(input){const ocpd=standardExact(input.ocpdA),mat=one(input.material,['Cu','Al'],'EGC material');for(const row of R.egcTable)if(ocpd<=row.maxA)return{module:'egc',status:'PASS',ocpdA:ocpd,material:mat,size:row[mat],reference:R.references.egc,warnings:['Table 250.122 gives a minimum. Verify 250.122 special rules, fault-current path, parallel conductors, motor-circuit provisions and installation restrictions.']};throw new Error('OCPD exceeds supported Table 250.122 range')}
function evse(input){const load=num(input.maxLoadA,'EVSE maximum load amps'),v=num(input.voltage,'voltage');one(v,[120,208,240,277,480],'voltage');const min=load*R.evse.continuousFactor,candidate=standardUp(min);if(!candidate)throw new Error('EVSE OCPD exceeds Phase 3 supported range');return{module:'evse',status:'PASS',result:{maxLoadA:load,voltage:v,loadVA:Math.round(load*v),minimumCircuitAmpacityA:Math.round(min*100)/100,minimumOcpdA:Math.round(min*100)/100,standardOcpdCandidateA:candidate,individualBranchCircuit:true},reference:R.references.evse,warnings:['EV charging is treated as continuous duty in this supported path. Verify equipment listing, manufacturer instructions, receptacle/hardwire requirements, GFCI where applicable, local AHJ and any load-management/EMS provisions before installation.','This tool sizes from the entered maximum equipment load. Do not substitute vehicle charging preference for the EVSE maximum load unless the listed equipment/load-management system establishes that limit.']}}
function hvac(input){const mca=num(input.mcaA,'MCA'),mocp=num(input.mocpA,'MOCP'),actual=standardExact(input.ocpdA),v=num(input.voltage,'voltage');if(mocp<mca)throw new Error('MOCP below MCA is inconsistent with this Phase 3 nameplate workflow; verify equipment marking');if(actual>mocp)throw new Error('Selected OCPD exceeds equipment MOCP');const ground=egc({ocpdA:actual,material:input.egcMaterial||'Cu'});return{module:'hvac',status:'PASS',result:{voltage:v,mcaA:mca,mocpA:mocp,selectedOcpdA:actual,minimumConductorAmpacityA:mca,egcMaterial:ground.material,egcSize:ground.size},reference:R.references.hvac,warnings:['Use the listed equipment nameplate MCA for minimum branch-circuit conductor ampacity and do not exceed nameplate MOCP. Do not derive HVAC electrical sizing from tonnage.','Conductor insulation, terminals, ambient/CCC adjustment, disconnect, GFCI, manufacturer instructions and local amendments remain separate checks.']}}
function motor(input){const flc=num(input.tableFlcA,'motor table FLC'),np=num(input.nameplateA,'motor nameplate current');const device=one(input.deviceType,['nonTimeDelayFuse','timeDelayFuse','inverseTimeBreaker'],'motor SC/GF device');const minCond=flc*R.motor.conductorFactor;const rawMax=flc*R.motor.commonAcScgf[device],ocpd=standardUp(rawMax);if(!ocpd)throw new Error('Motor OCPD exceeds Phase 3 supported range');const high=!!input.serviceFactor115OrTempRise40,overload=np*(high?R.motor.overloadHighSfFactor:R.motor.overloadOtherFactor);const ground=egc({ocpdA:ocpd,material:input.egcMaterial||'Cu'});return{module:'motor',status:'PASS',result:{tableFlcA:flc,nameplateA:np,minimumBranchConductorAmpacityA:Math.round(minCond*100)/100,deviceType:device,table43052CalculatedMaxA:Math.round(rawMax*100)/100,standardOcpdCandidateA:ocpd,overloadMaxA:Math.round(overload*100)/100,overloadFactor:high?1.25:1.15,egcMaterial:ground.material,egcSize:ground.size},reference:{conductors:R.references.motorConductors,overload:R.references.motorOverload,scgf:R.references.motorScgf,egc:R.references.egc},warnings:['Supported scope: one common AC motor, continuous duty, using FLC determined under 430.6(A)(1). Do not use nameplate current in place of required table FLC for conductor/SCGF sizing.','Design BE/CE, VFD/reduced-voltage starting, multispeed, wye-delta, wound-rotor, synchronous, DC, group installations and special-duty motors require a detailed Article 430 calculation.','The displayed 430.52 value is a maximum planning candidate for the selected device type; starting problems and permitted increases/exceptions require the actual Article 430 rules.']}}
const SIZE_ORDER=['14','12','10','8','6','4','3','2','1','1/0','2/0','3/0','4/0','250 kcmil','300 kcmil','350 kcmil','400 kcmil','500 kcmil','600 kcmil','700 kcmil','750 kcmil','800 kcmil','900 kcmil','1000 kcmil','1100 kcmil','1200 kcmil','1250 kcmil','1500 kcmil','1750 kcmil','2000 kcmil'];
function idx(s){const i=SIZE_ORDER.indexOf(String(s));if(i<0)throw new Error('unsupported service conductor size');return i}
function gecBase(serviceMat,size,gecMat){one(serviceMat,['Cu','Al'],'service conductor material');one(gecMat,['Cu','Al'],'GEC material');const i=idx(size);let row;if(serviceMat==='Cu'){const limits=['2','1/0','3/0','350 kcmil','600 kcmil','1100 kcmil'];for(let n=0;n<limits.length;n++)if(i<=idx(limits[n])){row=R.gecTable[n];break}}else{const limits=['1/0','3/0','250 kcmil','500 kcmil','900 kcmil','1750 kcmil'];for(let n=0;n<limits.length;n++)if(i<=idx(limits[n])){row=R.gecTable[n];break}}if(!row)row=R.gecTable[R.gecTable.length-1];return row[gecMat]}
function groundingElectrode(input){const sm=one(input.serviceMaterial,['Cu','Al'],'service conductor material'),gm=one(input.gecMaterial,['Cu','Al'],'GEC material'),size=String(input.serviceConductorSize||''),electrode=one(input.electrodeType,['table','rod-pipe-plate','concrete-encased','ground-ring'],'electrode type');let base=gecBase(sm,size,gm),out=base,status='PASS',note='Table 250.66 base size';if(electrode==='rod-pipe-plate'){out=gm==='Cu'?(idx(base)>idx('6')?'6':base):(idx(base)>idx('4')?'4':base);note='250.66 rod/pipe/plate cap applied'}else if(electrode==='concrete-encased'){if(gm!=='Cu')throw new Error('Phase 3 concrete-encased electrode automation supports copper GEC only; verify 250.64 installation restrictions for other materials');out=idx(base)>idx('4')?'4':base;note='250.66 concrete-encased electrode cap applied'}else if(electrode==='ground-ring'){status='REVIEW';out=null;note='Ground-ring GEC cannot be larger than the ground-ring conductor; enter/verify actual ring design'}return{module:'gec',status:status,result:{serviceMaterial:sm,serviceConductorSize:size,gecMaterial:gm,table25066BaseSize:base,electrodeType:electrode,gecSize:out,note:note},reference:R.references.gec,warnings:['Table 250.66 is only the base sizing path. Verify electrode-specific rules, parallel conductor equivalent area, separately derived systems, aluminum installation restrictions, bonding and actual grounding electrode system.']}}
function feeder(input){const cont=num(input.continuousA,'continuous load amps',true),non=num(input.noncontinuousA,'noncontinuous load amps',true);if(cont===0&&non===0)throw new Error('at least one feeder load must be greater than zero');const min=non+1.25*cont,candidate=standardUp(min);if(!candidate)throw new Error('feeder exceeds Phase 3 supported range');const ground=egc({ocpdA:candidate,material:input.egcMaterial||'Cu'});return{module:'feeder',status:'REVIEW',result:{continuousA:cont,noncontinuousA:non,minimumAmpacityA:Math.round(min*100)/100,planningOcpdCandidateA:candidate,egcMaterial:ground.material,egcSize:ground.size},reference:R.references.feederContinuous,warnings:['OCPD is a planning candidate, not an automatic final selection. Verify 215, 240.4, 240.6, conductor ampacity/terminal limits, adjustment/correction factors, neutral load and all applicable equipment articles.','EGC result assumes the displayed planning OCPD is actually selected; recalculate grounding if the final OCPD changes.']}}
root.BrunoPhase3=Object.freeze({evse,hvac,motor,egc,groundingElectrode,feeder,_test:{standardUp,gecBase}});
})(window);
