const { test, expect } = require('@playwright/test');
const fs = require('fs');

const JOB_KEY='bruno-electric-v1';
const runtimeErrors=new WeakMap();
// Binding Browser E2E Amendment permits an explicit allowlist with a documented reason.
// Chromium emits this diagnostic because frame-ancestors is ineffective when delivered by meta CSP;
// it is a browser policy warning, not an application runtime failure. Every other console error stays fatal.
const ALLOWED_CONSOLE_ERRORS=new Set(["The Content Security Policy directive 'frame-ancestors' is ignored when delivered via a <meta> element."]);
function baseJob(name='Contract Audit Job'){
  return {
    id:'e2e-contract-'+String(name).toLowerCase().replace(/[^a-z0-9]+/g,'-'),
    quote:{customer:name,jobNumber:'E2E-C-001',proposalNumber:'PC-001',date:'2026-09-16'},
    company:{name:'Bruno Electric Services LLC'},catalog:[],materialsUsed:[],materialsUnresolved:[],
    personnel:{employees:[],burden:[]},electricalTasks:[],electricalTaskActiveId:null,
    changeOrders:[],summary:{},residentialHistory:[],necEdition:'2026 NEC',jurisdiction:'Texas'
  };
}
function errorsFor(page){
  let rows=runtimeErrors.get(page);if(rows)return rows;rows=[];runtimeErrors.set(page,rows);
  page.on('pageerror',e=>rows.push('pageerror: '+e.message));
  page.on('console',m=>{if(m.type()==='error'){const text=m.text();if(!ALLOWED_CONSOLE_ERRORS.has(text))rows.push('console.error: '+text);}});
  page.on('response',r=>{if(['script','serviceworker'].includes(r.request().resourceType())&&r.status()>=400)rows.push(`required ${r.request().resourceType()} ${r.status()}: ${r.url()}`);});
  page.on('requestfailed',r=>{if(['script','serviceworker'].includes(r.resourceType()))rows.push(`required ${r.resourceType()} failed: ${r.url()} · ${(r.failure()||{}).errorText||''}`);});
  return rows;
}
test.beforeEach(async({page})=>{errorsFor(page);});
test.afterEach(async({page},testInfo)=>{const rows=errorsFor(page);if(rows.length)await testInfo.attach('runtime-errors.txt',{body:Buffer.from(rows.join('\n')),contentType:'text/plain'});expect(rows,rows.join('\n')).toEqual([]);});
async function seed(page,job=baseJob()){await page.addInitScript(([k,v])=>{if(sessionStorage.getItem('__bruno_contract_seeded')==='1')return;localStorage.setItem(k,JSON.stringify(v));sessionStorage.setItem('__bruno_contract_seeded','1');},[JOB_KEY,job]);}
async function open(page,path){await page.goto(path,{waitUntil:'domcontentloaded'});await page.waitForTimeout(450);expect(errorsFor(page),errorsFor(page).join('\n')).toEqual([]);}
function desktopOnly(testInfo){return testInfo.project.name!=='chromium-desktop';}
async function openTool(page,id){const picker=page.locator('#be-tool-select');if(await picker.isVisible())await picker.selectOption(id);else{const b=page.locator(`#tool-nav [data-tool="${id}"]`);await expect(b).toBeVisible();await b.click();}await expect(page.locator(`#tool-${id}`)).toBeVisible();}
async function openAdvanced(page){const d=page.locator('#tool-tasks details.et-advanced');await expect(d).toBeAttached();if((await d.getAttribute('open'))===null)await d.locator('summary').click();}
async function fillTask(page,overrides={}){const x=Object.assign({load:'20',voltage:'240',phase:'1',distance:'50',material:'Cu',install:'EMT',conductor:'THHN_THWN2',basis:'NONCONTINUOUS',vd:'3',ambient:'30',ccc:'2',terminal:'75',parallel:'0',maxSize:'',raceway:'SEPARATE_SETS',ocpd:'20',neutral:'NONE',egc:'Cu'},overrides);await page.locator('#et-load').fill(x.load);await page.locator('#et-voltage').selectOption(x.voltage);await page.locator('#et-phase').selectOption(x.phase);await page.locator('#et-distance').fill(x.distance);await page.locator('#et-material').selectOption(x.material);await page.locator('#et-install').selectOption(x.install);await page.locator('#et-conductor').selectOption(x.conductor);await page.locator('#et-load-basis').selectOption(x.basis);await page.locator('#et-vd').fill(x.vd);await openAdvanced(page);await page.locator('#et-ambient').fill(x.ambient);await page.locator('#et-ccc').fill(x.ccc);await page.locator('#et-terminal').selectOption(x.terminal);await page.locator('#et-parallel').selectOption(x.parallel);await page.locator('#et-max-size').fill(x.maxSize);await page.locator('#et-raceway-strategy').selectOption(x.raceway);await page.locator('#et-ocpd').fill(x.ocpd);await page.locator('#et-neutral-mode').selectOption(x.neutral);await page.locator('#et-egc-material').selectOption(x.egc);}
async function notCoveredByBottomNav(page,selector){const loc=page.locator(selector);await loc.scrollIntoViewIfNeeded();await expect(loc).toBeVisible();const covered=await page.evaluate(sel=>{const el=document.querySelector(sel),nav=document.getElementById('be-tools-bottom');if(!el||!nav||getComputedStyle(nav).display==='none')return false;const a=el.getBoundingClientRect(),n=nav.getBoundingClientRect();return a.bottom>n.top&&a.top<n.bottom;},selector);expect(covered).toBe(false);}

// CAP-JOB-001 / CAP-JOB-002 · E2E-02 contract closure: A -> B -> A restoration.
test('E2E-02 contract closure restores Job A after Job B replacement',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');await seed(page);await open(page,'/index.html');page.on('dialog',d=>d.accept());const a=baseJob('JOB-A-ROUNDTRIP'),b=baseJob('JOB-B-ROUNDTRIP');a.materialsUsed=[{item:'A-isolated',qty:2,unitCost:11,units:'EA'}];b.materialsUsed=[{item:'B-isolated',qty:4,unitCost:22,units:'EA'}];const env=x=>({brunoExportType:'job',brunoExportVersion:1,appVersion:'e2e-contract',exportedAt:new Date().toISOString(),payload:x}),input=page.locator('#btn-import');const importJob=async(name,j)=>{await input.setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(env(j)))});await expect.poll(()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)).quote.customer,JOB_KEY)).toBe(j.quote.customer);};await importJob('a.json',a);await expect.poll(()=>page.evaluate(k=>(JSON.parse(localStorage.getItem(k)).materialsUsed||[]).map(x=>x.item),JOB_KEY)).toEqual(['A-isolated']);await importJob('b.json',b);let state=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),JOB_KEY);expect(state.materialsUsed.map(x=>x.item)).toEqual(['B-isolated']);expect(state.materialsUsed.some(x=>x.item==='A-isolated')).toBe(false);await importJob('a-again.json',a);state=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),JOB_KEY);expect(state.materialsUsed.map(x=>x.item)).toEqual(['A-isolated']);expect(state.materialsUsed[0].qty).toBe(2);expect(state.materialsUsed.some(x=>x.item==='B-isolated')).toBe(false);});

// CAP-CAT-001 / CAP-COST-001 / CAP-COST-002 · E2E-03 quantity edit persistence.
test('E2E-03 contract closure edits standard material quantity and persists reload',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');const job=baseJob();job.catalog=[{id:'ecat-contract-breaker',category:'SERVICE / PANELS',item:'Contract 20A breaker',units:'EA',unitCost:15,yourCost:7.5,vendor:'E2E',part:'CB20',priceStatus:'PRICED'}];await seed(page,job);await open(page,'/index.html#be=ESTIMATE&tab=catalog');await page.locator('#cat-search').fill('Contract 20A breaker');const row=page.locator('#cat-groups tr').filter({hasText:'Contract 20A breaker'}).first();await expect(row).toBeVisible();await row.locator('.cat-add').click();await page.goto('/index.html#be=ESTIMATE&tab=materials');await expect(page.locator('#panel-materials')).toBeVisible();const used=page.locator('#mat-used-body tr').filter({hasText:'Contract 20A breaker'}).first();await expect(used).toBeVisible();await used.locator('.mat-qty').fill('3');await expect.poll(()=>page.evaluate(k=>{const j=JSON.parse(localStorage.getItem(k));const r=(j.materialsUsed||[]).find(x=>x.item==='Contract 20A breaker');return r&&r.qty;},JOB_KEY)).toBe(3);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#mat-used-body tr').filter({hasText:'Contract 20A breaker'}).first().locator('.mat-qty')).toHaveValue('3');});

// CAP-ET-003..009 · E2E-06 proves each selector reaches its intended advanced runtime label.
test('E2E-06 contract closure proves intended advanced template runtime',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');test.setTimeout(60000);await seed(page);await open(page,'/electrical-tools.html');await openTool(page,'tasks');const cases=[['BRANCH_CIRCUIT_RUN','Branch Circuit',{}],['EVSE_CIRCUIT','EVSE Circuit',{basis:'CONTINUOUS'}],['HVAC_CIRCUIT','HVAC Circuit',{load:'32',ocpd:'40'}],['MOTOR_CIRCUIT','Motor Circuit',{}],['TRANSFORMER_FEED','Transformer Feed',{load:'125',voltage:'480',phase:'3',ccc:'3',ocpd:'150'}],['GENERATOR_FEEDER','Generator Feeder',{load:'100',ocpd:'125'}],['LONG_DISTANCE_VD','Generic Long Run',{load:'30',distance:'1000',parallel:'1',ocpd:'30'}]];for(const[type,label,values]of cases){await page.locator('#et-type').selectOption(type);await expect(page.locator('#et-calculate')).toContainText(label);await fillTask(page,values);await page.locator('#et-calculate').click();await expect(page.locator('#et-status')).toContainText(label+' calculation completed');}});

// CAP-SOLVER-* · E2E-07 completes extracted facts through the normal explicit Calculate action.
test('E2E-07 contract closure solver known facts flow into explicit calculation',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');await seed(page);await open(page,'/electrical-tools.html');await openTool(page,'tasks');await page.locator('#et-solver-text').fill('I need a 100A panel 250 ft from service at 240 V.');await page.locator('#et-solver-extract').click();await expect(page.locator('#et-solver-known')).toContainText(/100|250|240/);await expect(page.locator('#et-solver-unresolved')).not.toBeEmpty();const before=await page.evaluate(k=>(JSON.parse(localStorage.getItem(k)).electricalTasks||[]).length,JOB_KEY);await page.locator('#et-solver-use').click();await expect(page.locator('#et-load')).toHaveValue('100');await expect(page.locator('#et-distance')).toHaveValue('250');await expect(page.locator('#et-voltage')).toHaveValue('240');expect(await page.evaluate(k=>(JSON.parse(localStorage.getItem(k)).electricalTasks||[]).length,JOB_KEY)).toBe(before);await fillTask(page,{load:'100',distance:'250',voltage:'240',ocpd:'100'});await page.locator('#et-calculate').click();await expect(page.locator('#et-calc-out')).toContainText(/PASS|NO SUPPORTED CONFIGURATION|REVIEW REQUIRED|BLOCKED/);expect(await page.evaluate(k=>(JSON.parse(localStorage.getItem(k)).electricalTasks||[]).length,JOB_KEY)).toBe(before);});

// CAP-QUOTE-* · E2E-08 uses representative live Job content and proves approval immutability.
test('E2E-08 contract closure live Job mutation does not rewrite approved quote',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');const job=baseJob('Quoted Content');job.materialsUsed=[{id:'quoted-mat',item:'Quoted material',qty:1,units:'EA',unitCost:100,costState:'RESOLVED'}];await seed(page,job);await open(page,'/index.html#be=BILLING&tab=quote');const beforeText=await page.locator('#q-total').textContent();const beforeNumber=Number(String(beforeText).replace(/[^0-9.-]/g,''));expect(beforeNumber).toBeGreaterThan(0);await page.locator('#qa-approve').click();const approved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).quoteLifecycle.approved.customerAmount,JOB_KEY);expect(approved).toBeGreaterThan(0);await page.goto('/index.html#be=ESTIMATE&tab=materials');const row=page.locator('#mat-used-body tr').filter({hasText:'Quoted material'}).first();await expect(row).toBeVisible();await row.locator('.mat-qty').fill('4');await page.goto('/index.html#be=BILLING&tab=quote');await expect.poll(async()=>Number(String(await page.locator('#q-total').textContent()).replace(/[^0-9.-]/g,''))).not.toBe(beforeNumber);const still=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).quoteLifecycle.approved.customerAmount,JOB_KEY);expect(still).toBe(approved);await page.locator('#qa-use-approved').click();await expect(page.locator('#qa-invoice-basis')).toContainText('$'+approved.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}));});

// CAP-IO-* / CAP-JOB-002 · E2E-09 imports the exact bytes produced by Export Job.
test('E2E-09 contract closure real exported JSON round-trips over replaced active state',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');const exported=baseJob('Export Roundtrip');exported.materialsUsed=[{id:'exp-used',item:'Exported used row',qty:2,units:'EA',unitCost:25,costState:'RESOLVED'}];exported.materialsUnresolved=[{id:'exp-unresolved',item:'Exported unresolved row',qty:1,units:'EA',unitCost:null,costState:'UNRESOLVED'}];await seed(page,exported);await open(page,'/index.html');await page.locator('#btn-compact-more').click();const downloadPromise=page.waitForEvent('download');await page.locator('#btn-export').click();const download=await downloadPromise;const path=await download.path();expect(path).toBeTruthy();const exportedBuffer=await fs.promises.readFile(path);const foreign=baseJob('Foreign Active');foreign.materialsUsed=[{item:'FOREIGN-ONLY',qty:9,unitCost:99,units:'EA'}];foreign.electricalTaskActiveId='foreign-task';await page.evaluate(([k,v])=>localStorage.setItem(k,JSON.stringify(v)),[JOB_KEY,foreign]);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#q-customer')).toHaveValue('Foreign Active');page.on('dialog',d=>d.accept());await page.locator('#btn-import').setInputFiles({name:download.suggestedFilename(),mimeType:'application/json',buffer:exportedBuffer});await expect.poll(()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)).quote.customer,JOB_KEY)).toBe('Export Roundtrip');const restored=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),JOB_KEY);expect(restored.materialsUsed.some(x=>x.item==='Exported used row'&&x.qty===2)).toBe(true);expect(restored.materialsUnresolved.some(x=>x.item==='Exported unresolved row')).toBe(true);expect(restored.materialsUsed.some(x=>x.item==='FOREIGN-ONLY')).toBe(false);expect(restored.electricalTaskActiveId).toBe(null);});

// CAP-STORAGE-* · E2E-10 proves user entry survives reload and stale identifiers fail safely without overwriting Job state.
test('E2E-10 contract closure reload entry and stale identifier resilience',async({page},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop core journey.');await seed(page,baseJob('Reload Original'));await open(page,'/index.html#be=BILLING&tab=quote');await page.locator('#q-customer').fill('Reload Entry');await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#q-customer')).toHaveValue('Reload Entry');await page.evaluate(k=>{const j=JSON.parse(localStorage.getItem(k));j.electricalTaskActiveId='missing-task-id';j.electricalTasks=[];j.materialsUnresolved=[{item:'Legacy unresolved',qty:1,yourCost:''}];localStorage.setItem(k,JSON.stringify(j));},JOB_KEY);await page.reload({waitUntil:'domcontentloaded'});await page.goto('/electrical-tools.html');await openTool(page,'tasks');await expect(page.locator('#et-status')).not.toContainText(/TypeError|ReferenceError/);await page.goto('/index.html#be=BILLING&tab=quote');await expect(page.locator('#q-customer')).toHaveValue('Reload Entry');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).electricalTaskActiveId,JOB_KEY)).toBe('missing-task-id');});

// CAP-RESP-* · E2E-11 exercises long task form/results and verifies fixed phone nav does not cover primary actions.
test('E2E-11 contract closure long task workflow remains reachable at every viewport',async({page},testInfo)=>{await seed(page);await open(page,'/electrical-tools.html');await openTool(page,'tasks');await fillTask(page);await notCoveredByBottomNav(page,'#et-calculate');await page.locator('#et-calculate').click();await expect(page.locator('#et-calc-out')).toContainText('PASS');await expect(page.locator('#et-grounding-out')).toContainText('STAGE 4 PASS');await notCoveredByBottomNav(page,'#et-save');await notCoveredByBottomNav(page,'#et-solver-extract');expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(2);if(testInfo.project.name==='chromium-phone')await expect(page.locator('#be-tools-bottom')).toBeVisible();else await expect(page.locator('#be-tools-bottom')).toBeHidden();});

// CAP-PWA-* · E2E-12 proves owned-cache cleanup preserves unrelated cache, then proves offline core shell.
test('E2E-12 contract closure service-worker cache ownership and offline shell',async({page,context},testInfo)=>{test.skip(desktopOnly(testInfo),'Desktop service-worker journey.');await seed(page);await open(page,'/index.html');await expect.poll(()=>page.evaluate(async()=>!!(navigator.serviceWorker&&await navigator.serviceWorker.ready))).toBe(true);await page.evaluate(async()=>{const unrelated=await caches.open('unrelated-e2e-cache');await unrelated.put('./unrelated-e2e.txt',new Response('keep'));const ownedOld=await caches.open('bruno-electric-v1');await ownedOld.put('./legacy-e2e.txt',new Response('old'));const reg=await navigator.serviceWorker.getRegistration();if(reg)await reg.unregister();await navigator.serviceWorker.register('./sw.js');});await page.reload({waitUntil:'domcontentloaded'});await expect.poll(()=>page.evaluate(async()=>!!(navigator.serviceWorker&&await navigator.serviceWorker.ready))).toBe(true);const names=await page.evaluate(()=>caches.keys());expect(names).toContain('bruno-electric-v69');expect(names).toContain('unrelated-e2e-cache');expect(names).not.toContain('bruno-electric-v1');expect(await page.evaluate(async()=>{const r=await caches.match('./unrelated-e2e.txt');return r&&r.text();})).toBe('keep');await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('body')).toBeVisible();await page.goto('/electrical-tools.html',{waitUntil:'domcontentloaded'});await expect(page.locator('#tool-host')).toBeVisible();await context.setOffline(false);});