'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}

var CAT=global.BrunoElectricalCatalogV1,BOM=global.BrunoElectricBOM;
test('catalog seed preserves existing price and metadata',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:7.77,vendor:'CUSTOM',notes:'keep me',futureMeta:{x:1}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.unitCost,9.99);is(row.yourCost,7.77);is(row.vendor,'CUSTOM');is(row.notes,'keep me');is(row.futureMeta.x,1)});
test('catalog seed preserves explicit yourCost zero',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:0,vendor:'ZERO',futureMeta:{x:2}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.yourCost,0);is(row.unitCost,9.99);is(row.vendor,'ZERO');is(row.futureMeta.x,2)});
test('catalog seed is idempotent',function(){var once=CAT.mergeMissing([]),twice=CAT.mergeMissing(once);is(twice.length,once.length)});
test('catalog normalized-name match prevents duplicate',function(){var existing=[{id:'custom-id',item:'  12   AWG CU THHN/THWN-2  ',unitCost:3}];var merged=CAT.mergeMissing(existing);var matches=merged.filter(function(x){return String(x.item).trim().toLowerCase().replace(/\s+/g,' ')==='12 awg cu thhn/thwn-2'});is(matches.length,1)});
test('catalog ID collision preserves existing row without starter duplicate',function(){var existing=[{id:'ecat-thhn-cu-12',item:'Custom renamed conductor',unitCost:12,futureMeta:'keep'}];var merged=CAT.mergeMissing(existing);var idRows=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'});is(idRows.length,1);is(idRows[0].item,'Custom renamed conductor');is(idRows[0].futureMeta,'keep')});

test('BOM replacement preserves manual and other-source rows',function(){var state={catalog:[{id:'c1',item:'New G',units:'EA',unitCost:5,yourCost:3},{id:'c2',item:'New H',units:'EA',unitCost:6,yourCost:4}],materialsUsed:[{item:'A'},{item:'B'},{item:'C',generatedBy:{source:'ampacity-phase1'}},{item:'D',generatedBy:{source:'ampacity-phase1'}},{item:'E',generatedBy:{source:'conduit-phase1'}},{item:'F',generatedBy:{source:'conduit-phase1'}}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('ampacity-phase1',[{item:'New G',qty:1},{item:'New H',qty:1}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));var names=saved.materialsUsed.map(function(x){return x.item});is(names.join('|'),'A|B|E|F|New G|New H')});
test('BOM uses existing user yourCost and tags source/version',function(){var state={catalog:[{id:'c1',item:'Wire',units:'FT',unitCost:9,yourCost:4.25,lastPriceUpdate:'2026-09-14'}],materialsUsed:[{item:'manual'}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire',qty:10,version:'v9'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[1];is(row.unitCost,4.25);is(row.generatedBy.source,'test-source');is(row.generatedBy.version,'v9');is(row.units,'FT')});
test('BOM explicit yourCost zero stays resolved zero and flags Field Verify',function(){var state={catalog:[{id:'c1',item:'Wire Zero',units:'FT',unitCost:9,yourCost:0,lastPriceUpdate:'2026-09-14'}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire Zero',qty:10}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.unitCost,0);is(row.catalogMatchId,'c1');is(row.bomStatus,'Field Verify')});
test('BOM blank yourCost never falls back to Customer Price',function(){var state={catalog:[{id:'c0',item:'Unknown Cost',units:'EA',unitCost:100,yourCost:''}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost',qty:2}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.catalogMatchId,'c0');is(row.unitCost,0);is(row.bomStatus,'Unresolved')});
test('BOM caller status cannot mask unresolved contractor cost',function(){var state={catalog:[{id:'c0',item:'Unknown Cost Status',units:'EA',unitCost:75,yourCost:null}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost Status',qty:1,status:'Field Verify'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.unitCost,0);is(row.bomStatus,'Unresolved')});
test('BOM unresolved item remains reviewable at zero',function(){var state={catalog:[],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown',qty:1,status:'Field Verify'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.catalogMatchId,null);is(row.unitCost,0);is(row.bomStatus,'Unresolved')});

if(typeof require==='function'){
  var fs=require('fs'),path=require('path'),sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),workspace=fs.readFileSync(path.join(__dirname,'..','electric-workspace.js'),'utf8'),takeoffUi=fs.readFileSync(path.join(__dirname,'..','electrical-residential-takeoff-ui.js'),'utf8'),toolShell=fs.readFileSync(path.join(__dirname,'..','electrical-tools-shell.js'),'utf8'),toolsHtml=fs.readFileSync(path.join(__dirname,'..','electrical-tools.html'),'utf8');
  test('service worker optional assets cannot poison core install',function(){ok(sw.indexOf('OPTIONAL_SHELL.map')>=0&&sw.indexOf('catch(() => null)')>=0,'optional cache failure isolation missing')});
  test('service worker cache bumped for mobile embed correction',function(){ok(sw.indexOf("bruno-electric-v32")>=0,'v32 cache missing')});
  test('mobile workspace uses five primary sections',function(){['Job','Estimate','Electrical','Billing','More'].forEach(function(label){ok(workspace.indexOf("label:'"+label+"'")>=0,label+' mobile nav missing')});ok(workspace.indexOf('grid-template-columns:repeat(5,1fr)')>=0,'five-column mobile nav missing');ok(workspace.indexOf('body.be-workspace #nav-tabs{display:none!important}')>=0,'legacy mobile tab strip not hidden')});
  test('mobile primary navigation opens sections without popup sheet architecture',function(){ok(workspace.indexOf('be-mobile-section-nav')>=0,'in-page section navigation missing');ok(workspace.indexOf('be-mobile-sheet')<0,'popup mobile sheet still present');ok(workspace.indexOf('be-mobile-backdrop')<0,'popup backdrop still present');ok(workspace.indexOf('function openGroup')>=0,'section routing missing')});
  test('mobile workbar uses dark application controls',function(){var mobile=workspace.indexOf('@media (max-width:767.98px)');var body=workspace.slice(mobile);ok(body.indexOf('.be-workbar button{appearance:none')>=0,'mobile workbar button reset missing');ok(body.indexOf('background:var(--bg-card);color:var(--text)')>=0,'mobile workbar dark colors missing')});
  test('Electrical stays inside unified Bruno Electric shell',function(){ok(workspace.indexOf('panel-electrical-workspace')>=0,'embedded electrical panel missing');ok(workspace.indexOf('electrical-tools.html#embedded')>=0,'embedded Electrical Tools frame missing');ok(workspace.indexOf("location.href='./electrical-tools.html'")<0,'Electrical still navigates away from app shell');ok(workspace.indexOf("data-go=\"__tools\"")>=0,'workspace Electrical route missing')});
  test('Electrical Tools permits same-origin embed but blocks foreign ancestors',function(){ok(toolsHtml.indexOf("frame-ancestors 'self'")>=0,'same-origin frame policy missing');ok(toolsHtml.indexOf("frame-ancestors 'none'")<0,'self embed still blocked by CSP')});
  test('browser-mode mobile nav reserves overlay-safe right gutter',function(){ok(workspace.indexOf("classList.add('be-browser-mode')")>=0,'browser mode detection missing');ok(workspace.indexOf('body.be-browser-mode .be-mobile-bottom')>=0,'browser overlay gutter rule missing');ok(workspace.indexOf('72px + env(safe-area-inset-right')>=0,'overlay-safe gutter size missing')});
  test('Electrical Tools mobile architecture uses categorized compact picker',function(){['Core Calculators','Residential','Equipment & Distribution','Catalog & Reference'].forEach(function(label){ok(toolShell.indexOf("label:'"+label+"'")>=0,label+' tool category missing')});ok(toolShell.indexOf("ids:['res','res-takeoff']")>=0,'Residential Full Takeoff not grouped under Residential');ok(toolShell.indexOf("ids:['ev3','hv3','mo3','gr3','fd3']")>=0,'equipment tools grouping missing');ok(toolShell.indexOf("indexOf('embedded')")>=0,'embedded Electrical Tools mode missing');ok(toolsHtml.indexOf('./electrical-tools-shell.js')>=0,'tools shell not loaded by page')});
  test('takeoff Save always recalculates current DOM before persistence',function(){var start=takeoffUi.indexOf('function saveBom()');var end=takeoffUi.indexOf('function install()',start);var body=takeoffUi.slice(start,end);ok(body.indexOf('render();')>=0,'save does not force current render/recalculation');ok(body.indexOf('if(!last)render()')<0,'save still conditionally reuses stale last');ok(body.indexOf("status:'Field Verify'")<0,'save still masks unresolved status')});
}
global.BRUNO_TEST_RESULTS=out;
})();
