'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}
var CAT=global.BrunoElectricalCatalogV1,BOM=global.BrunoElectricBOM;
test('catalog seed preserves existing price and metadata',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:7.77,vendor:'CUSTOM',notes:'keep me',futureMeta:{x:1}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.unitCost,9.99);is(row.yourCost,7.77);is(row.vendor,'CUSTOM');is(row.notes,'keep me');is(row.futureMeta.x,1)});
test('catalog seed preserves explicit yourCost zero',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:0,vendor:'ZERO',futureMeta:{x:2}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.yourCost,0);is(row.unitCost,9.99);is(row.vendor,'ZERO');is(row.futureMeta.x,2)});
test('catalog seed is idempotent',function(){var once=CAT.mergeMissing([]),twice=CAT.mergeMissing(once);is(twice.length,once.length)});
test('catalog normalized-name match prevents duplicate',function(){var existing=[{id:'custom-id',item:'  12   AWG CU THHN/THWN-2  ',unitCost:3}];var merged=CAT.mergeMissing(existing);var matches=merged.filter(function(x){return String(x.item).trim().toLowerCase().replace(/\s+/g,' ')==='12 awg cu thhn/thwn-2'});is(matches.length,1)});
test('catalog ID collision preserves existing row without starter duplicate',function(){var existing=[{id:'ecat-thhn-cu-12',item:'Custom renamed conductor',unitCost:12,futureMeta:'keep'}];var merged=CAT.mergeMissing(existing);var idRows=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'});is(idRows.length,1);is(idRows[0].item,'Custom renamed conductor');is(idRows[0].futureMeta,'keep')});
test('BOM replacement preserves manual and other-source rows',function(){var state={catalog:[{id:'c1',item:'New G',units:'EA',unitCost:5,yourCost:3},{id:'c2',item:'New H',units:'EA',unitCost:6,yourCost:4}],materialsUsed:[{item:'A'},{item:'B'},{item:'C',generatedBy:{source:'ampacity-phase1'}},{item:'D',generatedBy:{source:'ampacity-phase1'}},{item:'E',generatedBy:{source:'conduit-phase1'}},{item:'F',generatedBy:{source:'conduit-phase1'}}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('ampacity-phase1',[{item:'New G',qty:1},{item:'New H',qty:1}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));var names=saved.materialsUsed.map(function(x){return x.item});is(names.join('|'),'A|B|E|F|New G|New H')});
test('BOM uses existing user yourCost and tags source/version',function(){var state={catalog:[{id:'c1',item:'Wire',units:'FT',unitCost:9,yourCost:4.25,lastPriceUpdate:'2026-09-14'}],materialsUsed:[{item:'manual'}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire',qty:10,version:'v9'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[1];is(row.unitCost,4.25);is(row.generatedBy.source,'test-source');is(row.generatedBy.version,'v9');is(row.units,'FT')});
test('BOM explicit yourCost zero stays resolved zero and flags Field Verify',function(){var state={catalog:[{id:'c1',item:'Wire Zero',units:'FT',unitCost:9,yourCost:0,lastPriceUpdate:'2026-09-14'}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire Zero',qty:10}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1')),row=saved.materialsUsed[0];is(row.unitCost,0);is(row.costState,'RESOLVED');is(row.catalogMatchId,'c1');is(row.bomStatus,'Field Verify');is((saved.materialsUnresolved||[]).length,0)});
test('BOM blank yourCost is stored first-class unresolved outside numeric materialsUsed',function(){var state={catalog:[{id:'c0',item:'Unknown Cost',units:'EA',unitCost:100,yourCost:''}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost',qty:2}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(saved.materialsUsed.length,0);is(saved.materialsUnresolved.length,1);var row=saved.materialsUnresolved[0];is(row.catalogMatchId,'c0');is(row.unitCost,null);is(row.costState,'UNRESOLVED');is(row.unresolvedReason,'YOUR_COST_UNRESOLVED');is(row.bomStatus,'Unresolved')});
test('BOM caller status cannot mask unresolved contractor cost',function(){var state={catalog:[{id:'c0',item:'Unknown Cost Status',units:'EA',unitCost:75,yourCost:null}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost Status',qty:1,status:'Field Verify'}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(saved.materialsUsed.length,0);var row=saved.materialsUnresolved[0];is(row.unitCost,null);is(row.costState,'UNRESOLVED');is(row.bomStatus,'Unresolved')});
test('BOM unmatched item remains reviewable unresolved outside numeric cost math',function(){var state={catalog:[],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown',qty:1,status:'Field Verify'}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(saved.materialsUsed.length,0);var row=saved.materialsUnresolved[0];is(row.catalogMatchId,null);is(row.unitCost,null);is(row.unresolvedReason,'CATALOG_UNMATCHED');is(row.bomStatus,'Unresolved')});
test('BOM recalculation promotes formerly unresolved row when Your Cost becomes known',function(){var state={catalog:[{id:'c1',item:'Promote Wire',units:'FT',unitCost:9,yourCost:''}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Promote Wire',qty:5}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(saved.materialsUsed.length,0);is(saved.materialsUnresolved.length,1);saved.catalog[0].yourCost=2.5;localStorage.setItem('bruno-electric-v1',JSON.stringify(saved));BOM.replaceGenerated('test-source',[{item:'Promote Wire',qty:5}]);saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(saved.materialsUnresolved.length,0);is(saved.materialsUsed.length,1);is(saved.materialsUsed[0].unitCost,2.5)});
if(typeof require==='function'){
 var fs=require('fs'),path=require('path'),sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),workspace=fs.readFileSync(path.join(__dirname,'..','electric-workspace.js'),'utf8'),bridge=fs.readFileSync(path.join(__dirname,'..','electric-navigation-bridge.js'),'utf8'),swRegister=fs.readFileSync(path.join(__dirname,'..','sw-register.js'),'utf8'),appNav=fs.readFileSync(path.join(__dirname,'..','electric-app-navigation.js'),'utf8'),takeoffUi=fs.readFileSync(path.join(__dirname,'..','electrical-residential-takeoff-ui.js'),'utf8'),liveEngine=fs.readFileSync(path.join(__dirname,'..','electric-residential-live.js'),'utf8'),liveLevels=fs.readFileSync(path.join(__dirname,'..','electric-residential-live-levels.js'),'utf8'),liveHistory=fs.readFileSync(path.join(__dirname,'..','electric-residential-live-history.js'),'utf8'),liveWorkspace=fs.readFileSync(path.join(__dirname,'..','electric-residential-live-workspace.js'),'utf8'),liveUi=fs.readFileSync(path.join(__dirname,'..','electrical-residential-live-ui.js'),'utf8'),liveLevelsUi=fs.readFileSync(path.join(__dirname,'..','electrical-residential-live-levels-ui.js'),'utf8'),toolShell=fs.readFileSync(path.join(__dirname,'..','electrical-tools-shell.js'),'utf8'),toolsHtml=fs.readFileSync(path.join(__dirname,'..','electrical-tools.html'),'utf8'),projectUi=fs.readFileSync(path.join(__dirname,'..','electrical-project-calculator-ui.js'),'utf8'),jobCostSem=fs.readFileSync(path.join(__dirname,'..','electric-job-material-cost-semantics.js'),'utf8');
 test('service worker optional assets cannot poison core install',function(){ok(sw.indexOf('OPTIONAL_SHELL.map')>=0&&sw.indexOf('catch(() => null)')>=0,'optional cache failure isolation missing')});
 test('service worker v45 caches project-first live residential and strict material-cost modules',function(){ok(sw.indexOf("bruno-electric-v45")>=0,'v45 cache missing');['electric-app-navigation.js','electric-navigation-bridge.js','electric-residential-live.js','electric-residential-live-levels.js','electric-residential-live-history.js','electric-residential-live-workspace.js','electrical-residential-live-ui.js','electrical-residential-live-levels-ui.js','electrical-project-calculator-ui.js','electric-job-material-cost-semantics.js'].forEach(function(name){ok(sw.indexOf("'./"+name+"'")>=0,name+' not cached')})});
 test('Job Materials unresolved display bridge is loaded and labels excluded cost',function(){ok(swRegister.indexOf('electric-job-material-cost-semantics.js')>=0,'job material cost semantics bootstrap missing');ok(jobCostSem.indexOf('materialsUnresolved')>=0,'unresolved store missing');ok(jobCostSem.indexOf('Excluded')>=0,'excluded display missing');ok(jobCostSem.indexOf('UNRESOLVED COST')>=0,'unresolved label missing')});
 test('shared navigation is single canonical five-section model',function(){['JOB','ESTIMATE','ELECTRICAL','BILLING','MORE'].forEach(function(k){ok(appNav.indexOf("key:'"+k+"'")>=0,k+' group missing');ok(workspace.indexOf("key:'"+k+"'")<0,'workspace duplicates '+k+' canonical group')});['Journal','Calculator','Job','Catalog','More'].forEach(function(label){ok(appNav.indexOf("label:'"+label+"'")>=0,label+' label missing')});ok(appNav.indexOf('workspaceHref')>=0,'canonical routing helper missing');ok(workspace.indexOf('var groups=NAV.groups')>=0,'workspace not consuming canonical groups directly');ok(workspace.indexOf('||[')<0,'workspace contains fallback IA array')});
 test('workspace loads shared navigation before enhancement',function(){ok(swRegister.indexOf('electric-app-navigation.js')>=0,'shared navigation loader missing');ok(swRegister.indexOf('n.onload=loadWorkspaceEnhancement')>=0,'workspace can load before navigation model')});
 test('workspace live residential total loads shared pricing engine first',function(){ok(swRegister.indexOf('electric-residential-pricing.js')>=0,'residential pricing bootstrap missing');ok(swRegister.indexOf('p.onload=loadResidentialWorkspaceModule')>=0,'workspace pricing dependency order missing');ok(liveWorkspace.indexOf('BrunoResidentialPricing')>=0,'workspace not using shared pricing engine');ok(liveWorkspace.indexOf('priceRows')>=0,'workspace live repricing missing')});
 test('workspace has universal responsive breakpoints',function(){ok(workspace.indexOf('@media (max-width:767.98px)')>=0,'phone breakpoint missing');ok(workspace.indexOf('@media (min-width:768px) and (max-width:1199.98px)')>=0,'tablet breakpoint missing');ok(workspace.indexOf('@media (min-width:1200px)')>=0,'desktop breakpoint missing')});
 test('workspace uses same five primary sections on all viewports',function(){ok(workspace.indexOf('var groups=NAV.groups')>=0,'workspace not consuming shared groups');ok(workspace.indexOf('be-primary-btn')>=0,'tablet/desktop primary navigation missing');ok(workspace.indexOf("className='be-bottom")>=0,'phone primary navigation missing');ok(workspace.indexOf('grid-template-columns:repeat(5,1fr)')>=0,'five-column phone nav missing')});
 test('Electrical route is first-class page not iframe',function(){ok(workspace.indexOf("location.href='./electrical-tools.html'")>=0,'Electrical page route missing');ok(workspace.indexOf('<iframe')<0,'iframe architecture returned')});
 test('cross-page bridge restores group or exact tab',function(){ok(bridge.indexOf('URLSearchParams')>=0,'hash parser missing');ok(bridge.indexOf("p.get('tab')")>=0,'exact tab restore missing')});
 test('Electrical Tools consumes same navigation model across phone tablet desktop',function(){ok(toolsHtml.indexOf('./electric-app-navigation.js')>=0,'shared navigation script missing');ok(toolShell.indexOf('groups=NAV&&NAV.groups')>=0,'tools shell not consuming shared groups');ok(toolShell.indexOf('@media(max-width:767.98px)')>=0,'tools phone breakpoint missing');ok(toolShell.indexOf('@media(min-width:768px) and (max-width:1199.98px)')>=0,'tools tablet breakpoint missing');ok(toolShell.indexOf('@media(min-width:1200px)')>=0,'tools desktop breakpoint missing')});
 test('Electrical Tools prioritizes Project Calculator then live design',function(){['Project','Core Calculators','Equipment & Distribution','Catalog & Reference'].forEach(function(label){ok(toolShell.indexOf("label:'"+label+"'")>=0,label+' tool category missing')});ok(toolShell.indexOf("ids:['project','res-live','res','res-takeoff']")>=0,'project-first calculator group missing');ok(toolsHtml.indexOf('./electrical-project-calculator-ui.js')>=0,'project UI script missing');ok(projectUi.indexOf('Calculate project')>=0,'project Calculate action missing')});
 test('live residential UI saves project calculation and maintains live-priced archive',function(){ok(liveUi.indexOf('BrunoResidentialLive')>=0,'live UI engine binding missing');ok(liveUi.indexOf("addEventListener('input'")>=0,'live input recalculation missing');ok(liveUi.indexOf('Confirm & Save Project Calculation')>=0,'project save action missing');ok(liveUi.indexOf('Project Calculation Archive')>=0,'project archive UI missing');ok(liveUi.indexOf('lastPricing=P.priceRows(lastBom')>=0,'augmented BOM not live-priced');ok(liveUi.indexOf('Panel / service sizing')>=0,'panel/service result missing');ok(liveHistory.indexOf('residentialLiveActive')>=0,'active snapshot persistence missing');ok(liveHistory.indexOf("pricingMode='LIVE_CATALOG'")>=0,'live Catalog archive mode missing');ok(liveHistory.indexOf('delete s.pricing')>=0,'archive still persists stale pricing');ok(liveWorkspace.indexOf('Residential materials')>=0,'workspace material total bridge missing');ok(liveEngine.indexOf('NON-COMPLIANT')>=0,'live code validation state missing')});
 test('live residential levels expose dependency chain L0 through L6',function(){['L0','L1','L2','L3','L4','L5','L6'].forEach(function(x){ok(liveLevels.indexOf("id:'"+x+"'")>=0,x+' missing')});ok(liveLevelsUi.indexOf('affectedFrom')>=0,'level UI dependency highlighting missing')});
 test('Electrical Tools no longer claims ineffective frame-ancestors meta enforcement',function(){ok(toolsHtml.indexOf('frame-ancestors')<0,'ineffective frame-ancestors meta directive still present')});
 test('takeoff Save always recalculates current DOM before persistence',function(){var start=takeoffUi.indexOf('function saveBom()'),end=takeoffUi.indexOf('function install()',start),body=takeoffUi.slice(start,end);ok(body.indexOf('render();')>=0,'save does not force current render/recalculation');ok(body.indexOf('if(!last)render()')<0,'save still conditionally reuses stale last');ok(body.indexOf("status:'Field Verify'")<0,'save still masks unresolved status')});
}
global.BRUNO_TEST_RESULTS=out;
})();