'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}

var CAT=global.BrunoElectricalCatalogV1,BOM=global.BrunoElectricBOM;
test('catalog seed preserves existing price and metadata',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:7.77,vendor:'CUSTOM',notes:'keep me',futureMeta:{x:1}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.unitCost,9.99);is(row.yourCost,7.77);is(row.vendor,'CUSTOM');is(row.notes,'keep me');is(row.futureMeta.x,1)});
test('catalog seed preserves explicit yourCost zero',function(){var existing=[{id:'ecat-thhn-cu-12',item:'12 AWG Cu THHN/THWN-2',unitCost:9.99,yourCost:0,vendor:'ZERO',futureMeta:{x:2}}];var merged=CAT.mergeMissing(existing);var row=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'})[0];is(row.yourCost,0);is(row.unitCost,9.99);is(row.vendor,'ZERO');is(row.futureMeta.x,2)});
test('catalog seed is idempotent',function(){var once=CAT.mergeMissing([]),twice=CAT.mergeMissing(once);is(twice.length,once.length)});
test('catalog normalized-name match prevents duplicate',function(){var existing=[{id:'custom-id',item:'  12   AWG CU THHN/THWN-2  ',unitCost:3}];var merged=CAT.mergeMissing(existing);var matches=merged.filter(function(x){return String(x.item).trim().toLowerCase().replace(/\s+/g,' ')==='12 awg cu thhn/thwn-2'});is(matches.length,1)});
test('catalog ID collision preserves existing row without starter duplicate',function(){var existing=[{id:'ecat-thhn-cu-12',item:'Custom renamed conductor',unitCost:12,futureMeta:'keep'}];var merged=CAT.mergeMissing(existing);var idRows=merged.filter(function(x){return x.id==='ecat-thhn-cu-12'});is(idRows.length,1);is(idRows[0].item,'Custom renamed conductor');is(idRows[0].futureMeta,'keep')});

test('BOM replacement preserves manual and other-source rows',function(){var state={catalog:[{id:'c1',item:'New G',units:'EA',unitCost:5,yourCost:3},{id:'c2',item:'New H',units:'EA',unitCost:6,yourCost:4}],materialsUsed:[{item:'A'},{item:'B'},{item:'C',generatedBy:{source:'ampacity-phase1'}},{item:'D',generatedBy:{source:'ampacity-phase1'}},{item:'E',generatedBy:{source:'conduit-phase1'}},{item:'F',generatedBy:{source:'conduit-phase1'}}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('ampacity-phase1',[{item:'New G',qty:1},{item:'New H',qty:1}]);var saved=JSON.parse(localStorage.getItem('bruno-electric-v1'));var names=saved.materialsUsed.map(function(x){return x.item});is(names.join('|'),'A|B|E|F|New G|New H')});
test('BOM uses existing user yourCost and tags source/version',function(){var state={catalog:[{id:'c1',item:'Wire',units:'FT',unitCost:9,yourCost:4.25,lastPriceUpdate:'2026-09-14'}],materialsUsed:[{item:'manual'}]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire',qty:10,version:'v9'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[1];is(row.unitCost,4.25);is(row.generatedBy.source,'test-source');is(row.generatedBy.version,'v9');is(row.units,'FT')});
test('BOM explicit yourCost zero stays resolved zero and flags Field Verify',function(){var state={catalog:[{id:'c1',item:'Wire Zero',units:'FT',unitCost:9,yourCost:0,lastPriceUpdate:'2026-09-14'}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Wire Zero',qty:10}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.unitCost,0);is(row.catalogMatchId,'c1');is(row.bomStatus,'Field Verify')});
test('BOM blank yourCost never falls back to Customer Price',function(){var state={catalog:[{id:'c0',item:'Unknown Cost',units:'EA',unitCost:100,yourCost:''}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost',qty:2}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.catalogMatchId,'c0');is(row.unitCost,0);is(row.bomStatus,'Unresolved')});
test('BOM caller status cannot mask unresolved contractor cost',function(){var state={catalog:[{id:'c0',item:'Unknown Cost Status',units:'EA',unitCost:75,yourCost:null}],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown Cost Status',qty:1,status:'Field Verify'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.unitCost,0);is(row.bomStatus,'Unresolved')});
test('BOM unresolved item remains reviewable at zero',function(){var state={catalog:[],materialsUsed:[]};localStorage.setItem('bruno-electric-v1',JSON.stringify(state));BOM.replaceGenerated('test-source',[{item:'Unknown',qty:1,status:'Field Verify'}]);var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed[0];is(row.catalogMatchId,null);is(row.unitCost,0);is(row.bomStatus,'Unresolved')});

if(typeof require==='function'){
  var fs=require('fs'),path=require('path'),sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),workspace=fs.readFileSync(path.join(__dirname,'..','electric-workspace.js'),'utf8'),bridge=fs.readFileSync(path.join(__dirname,'..','electric-navigation-bridge.js'),'utf8'),swRegister=fs.readFileSync(path.join(__dirname,'..','sw-register.js'),'utf8'),appNav=fs.readFileSync(path.join(__dirname,'..','electric-app-navigation.js'),'utf8'),takeoffUi=fs.readFileSync(path.join(__dirname,'..','electrical-residential-takeoff-ui.js'),'utf8'),toolShell=fs.readFileSync(path.join(__dirname,'..','electrical-tools-shell.js'),'utf8'),toolsHtml=fs.readFileSync(path.join(__dirname,'..','electrical-tools.html'),'utf8');
  test('service worker optional assets cannot poison core install',function(){ok(sw.indexOf('OPTIONAL_SHELL.map')>=0&&sw.indexOf('catch(() => null)')>=0,'optional cache failure isolation missing')});
  test('service worker cache bumped for universal responsive shell',function(){ok(sw.indexOf("bruno-electric-v34")>=0,'v34 cache missing');ok(sw.indexOf("'./electric-app-navigation.js'")>=0,'shared app navigation not cached');ok(sw.indexOf("'./electric-navigation-bridge.js'")>=0,'navigation bridge not cached')});
  test('shared navigation is single canonical five-section model',function(){['JOB','ESTIMATE','ELECTRICAL','BILLING','MORE'].forEach(function(k){ok(appNav.indexOf("key:'"+k+"'")>=0,k+' group missing')});['Job','Estimate','Electrical','Billing','More'].forEach(function(label){ok(appNav.indexOf("label:'"+label+"'")>=0,label+' label missing')});ok(appNav.indexOf("workspaceHref")>=0,'canonical routing helper missing')});
  test('workspace loads shared navigation before enhancement',function(){ok(swRegister.indexOf('electric-app-navigation.js')>=0,'shared navigation loader missing');ok(swRegister.indexOf('n.onload=loadWorkspaceEnhancement')>=0,'workspace can load before navigation model')});
  test('workspace has universal responsive breakpoints',function(){ok(workspace.indexOf('@media (max-width:767.98px)')>=0,'phone breakpoint missing');ok(workspace.indexOf('@media (min-width:768px) and (max-width:1199.98px)')>=0,'tablet breakpoint missing');ok(workspace.indexOf('@media (min-width:1200px)')>=0,'desktop breakpoint missing');ok(workspace.indexOf('padding-left:92px')>=0,'tablet rail width missing');ok(workspace.indexOf('padding-left:244px')>=0,'desktop sidebar width missing')});
  test('workspace uses same five primary sections on all viewports',function(){ok(workspace.indexOf('groups=NAV&&NAV.groups')>=0,'workspace not consuming shared groups');ok(workspace.indexOf('be-primary-btn')>=0,'tablet/desktop primary navigation missing');ok(workspace.indexOf("className='be-bottom")>=0,'phone primary navigation missing');ok(workspace.indexOf('grid-template-columns:repeat(5,1fr)')>=0,'five-column phone nav missing');ok(workspace.indexOf('body.be-workspace #nav-tabs{display:none!important}')>=0,'legacy tab strip not hidden')});
  test('tablet exposes section choices in content while desktop exposes sidebar subitems',function(){ok(workspace.indexOf('.be-group-items{display:none!important}')>=0,'tablet subitem collapse missing');ok(workspace.indexOf('.be-section-nav{display:block')>=0,'tablet in-content section navigation missing');ok(workspace.indexOf('.be-group-items{padding:3px 0 0 22px}')>=0,'desktop subitem navigation missing');ok(workspace.indexOf('.be-section-nav{display:none!important}')>=0,'desktop duplicate section nav not suppressed')});
  test('Electrical route is first-class page not iframe',function(){ok(workspace.indexOf("location.href='./electrical-tools.html'")>=0,'Electrical page route missing');ok(workspace.indexOf('<iframe')<0,'iframe architecture returned');ok(workspace.indexOf('be-electrical-frame')<0,'iframe sizing architecture returned')});
  test('cross-page bridge restores group or exact tab',function(){ok(bridge.indexOf('URLSearchParams')>=0,'hash parser missing');ok(bridge.indexOf("p.get('tab')")>=0,'exact tab restore missing');ok(bridge.indexOf('.be-nav-btn[data-tab=')>=0,'desktop exact tab restore target missing');ok(bridge.indexOf('.be-primary-btn[data-group=')>=0,'group restore target missing')});
  test('mobile workbar uses dark application controls',function(){var mobile=workspace.indexOf('@media (max-width:767.98px)');var body=workspace.slice(mobile);ok(body.indexOf('.be-workbar')>=0,'mobile workbar missing');ok(workspace.indexOf('background:var(--bg-card);color:var(--text)')>=0,'workbar dark colors missing')});
  test('browser-mode phone nav reserves overlay-safe right gutter',function(){ok(workspace.indexOf("classList.add('be-browser-mode')")>=0,'browser mode detection missing');ok(workspace.indexOf('body.be-browser-mode .be-bottom')>=0,'browser overlay gutter rule missing');ok(workspace.indexOf('72px + env(safe-area-inset-right')>=0,'overlay-safe gutter size missing')});
  test('Electrical Tools consumes same navigation model across phone tablet desktop',function(){ok(toolsHtml.indexOf('./electric-app-navigation.js')>=0,'shared navigation script missing from tools page');ok(toolShell.indexOf('groups=NAV&&NAV.groups')>=0,'tools shell not consuming shared groups');ok(toolShell.indexOf('@media(max-width:767.98px)')>=0,'tools phone breakpoint missing');ok(toolShell.indexOf('@media(min-width:768px) and (max-width:1199.98px)')>=0,'tools tablet breakpoint missing');ok(toolShell.indexOf('@media(min-width:1200px)')>=0,'tools desktop breakpoint missing');ok(toolShell.indexOf('padding-left:92px')>=0,'tools tablet app rail missing');ok(toolShell.indexOf('padding-left:244px')>=0,'tools desktop app sidebar missing')});
  test('Electrical Tools keeps categorized calculator navigation',function(){['Core Calculators','Residential','Equipment & Distribution','Catalog & Reference'].forEach(function(label){ok(toolShell.indexOf("label:'"+label+"'")>=0,label+' tool category missing')});ok(toolShell.indexOf("ids:['res','res-takeoff']")>=0,'Residential Full Takeoff not grouped under Residential');ok(toolShell.indexOf("ids:['ev3','hv3','mo3','gr3','fd3']")>=0,'equipment tools grouping missing')});
  test('Electrical Tools no longer claims ineffective frame-ancestors meta enforcement',function(){ok(toolsHtml.indexOf('frame-ancestors')<0,'ineffective frame-ancestors meta directive still present')});
  test('takeoff Save always recalculates current DOM before persistence',function(){var start=takeoffUi.indexOf('function saveBom()');var end=takeoffUi.indexOf('function install()',start);var body=takeoffUi.slice(start,end);ok(body.indexOf('render();')>=0,'save does not force current render/recalculation');ok(body.indexOf('if(!last)render()')<0,'save still conditionally reuses stale last');ok(body.indexOf("status:'Field Verify'")<0,'save still masks unresolved status')});
}
global.BRUNO_TEST_RESULTS=out;
})();