'use strict';
(function(){
var fs=require('fs'),path=require('path');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}
var src=fs.readFileSync(path.join(__dirname,'..','electric-dispatch-journal-v2.js'),'utf8');
var nav=fs.readFileSync(path.join(__dirname,'..','electric-app-navigation.js'),'utf8');
var reg=fs.readFileSync(path.join(__dirname,'..','sw-register.js'),'utf8');
test('dispatch journal remains canonical home and supports period archive',function(){ok(nav.indexOf("label:'Journal'")>=0,'Journal primary nav missing');ok(nav.indexOf("defaultTab:'dispatch'")>=0,'dispatch not home default');['day','week','month','quarter'].forEach(function(x){ok(src.indexOf("value=\""+x+"\"")>=0,x+' view missing')})});
test('scheduled and cancelled calls are not earned',function(){ok(src.indexOf("var earned=c.status==='completed'")>=0,'earned status gate missing');ok(src.indexOf("if(!earned)return{gross:0,tax:0,net:0,hours:0,service:0,materials:0,tool:0}")>=0,'non-completed calls can still earn revenue')});
test('call journal supports quick and itemized materials',function(){['materialsMode','materialsTotal','materialItems','Quick materials total','Itemized materials list','materialsSubtotal','materialItemsSubtotal'].forEach(function(x){ok(src.indexOf(x)>=0,x+' materials support missing')});ok(src.indexOf("c.materialsMode==='itemized'?materialItemsSubtotal(c):Math.max(0,n(c.materialsTotal))")>=0,'materials subtotal mode boundary missing')});
test('optional tool and consumables charge is explicit and bounded to service price',function(){['toolFeeEnabled','toolFeePct','Tool / consumables charge','% of service / labor','toolCharge'].forEach(function(x){ok(src.indexOf(x)>=0,x+' tool charge contract missing')});ok(src.indexOf("Math.max(0,n(c.price))*Math.max(0,n(c.toolFeePct))/100")>=0,'tool fee basis is not service/labor price')});
test('mini invoice includes service materials tool and total',function(){['Mini invoice','Service / labor','Materials','Mini invoice total','invoiceTotal'].forEach(function(x){ok(src.indexOf(x)>=0,x+' mini invoice content missing')});ok(src.indexOf('Math.max(0,n(c&&c.price))+materialsSubtotal(c)+toolCharge(c)')>=0,'invoice total does not sum service materials and tool')});
test('legacy calls remain backward compatible with zero material and tool defaults',function(){ok(src.indexOf("if(!c.materialsMode)c.materialsMode=c.materialItems.length?'itemized':'quick'")>=0,'legacy materials mode normalization missing');ok(src.indexOf('if(c.materialsTotal==null)c.materialsTotal=0')>=0,'legacy materials total normalization missing');ok(src.indexOf('if(c.toolFeeEnabled==null)c.toolFeeEnabled=false')>=0,'legacy tool toggle normalization missing')});
test('helper configuration lives in settings and not in journal revision editors',function(){['helperEnabled','helperName','helperPayMode','helperRate','helperHours','Helper name','enable helper'].forEach(function(x){ok(src.indexOf(x)>=0,x+' helper setting missing')});['Save helper version','Disable from','data-hedit','data-hdel','dj-helper-add','Work days'].forEach(function(x){ok(src.indexOf(x)<0,'obsolete helper revision UI remains: '+x)})});
test('helper cost is date explicit and defaults off for new days',function(){ok(src.indexOf("data.helperDays[date]===true")>=0,'helper day is not explicit true-only');ok(src.indexOf("if(on)data.helperDays[selected]=true;else delete data.helperDays[selected]")>=0,'daily helper toggle persistence missing');ok(src.indexOf('Helper worked this day')>=0,'daily helper checkbox missing')});
test('period helper totals count only ON dates including zero-call days',function(){ok(src.indexOf('eachDate(r[0],r[1]')>=0,'period does not iterate calendar dates');ok(src.indexOf('helperCostForDate(data,s,day)')>=0,'helper day cost not evaluated independently of calls');ok(src.indexOf('helperDays++')>=0,'worked helper days not counted')});
test('legacy helper configuration migrates once without remaining as active runtime owner',function(){ok(src.indexOf('helperModelV2')>=0,'helper migration version missing');ok(src.indexOf('helperLegacyArchive=legacy')>=0,'legacy helper data not archived during migration');ok(src.indexOf('delete d.helpers')>=0,'legacy helper runtime array not retired after migration')});
test('completed calls snapshot applied owner tax',function(){ok(src.indexOf('taxPctApplied')>=0,'call tax snapshot missing');ok(src.indexOf("status==='completed'")>=0,'completed status snapshot boundary missing')});
test('obsolete global project mode loader is removed',function(){ok(reg.indexOf('electric-project-mode.js')<0,'old project mode selector still injected')});
global.BRUNO_TEST_RESULTS=out;
})();
