'use strict';
(function(){
var fs=require('fs'),path=require('path');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}
var src=fs.readFileSync(path.join(__dirname,'..','electric-dispatch-journal-v2.js'),'utf8');
var nav=fs.readFileSync(path.join(__dirname,'..','electric-app-navigation.js'),'utf8');
var reg=fs.readFileSync(path.join(__dirname,'..','sw-register.js'),'utf8');
test('dispatch journal remains canonical home and supports period archive',function(){ok(nav.indexOf("label:'Journal'")>=0,'Journal primary nav missing');ok(nav.indexOf("defaultTab:'dispatch'")>=0,'dispatch not home default');['day','week','month','quarter'].forEach(function(x){ok(src.indexOf("value=\""+x+"\"")>=0,x+' view missing')})});
test('scheduled and cancelled calls are not earned',function(){ok(src.indexOf("var earned=c.status==='completed'")>=0,'earned status gate missing');ok(src.indexOf("if(!earned)return{gross:0,tax:0,net:0,hours:0,service:0,materials:0,tool:0}")>=0,'non-completed calls can still earn revenue')});
test('call journal supports quick and itemized materials',function(){['materialsMode','materialsTotal','materialItems','Quick materials total','Itemized materials list','materialsSubtotal','materialItemsSubtotal'].forEach(function(x){ok(src.indexOf(x)>=0,x+' materials support missing')});ok(src.indexOf("c.materialsMode==='itemized'?materialItemsSubtotal(c):Math.max(0,n(c.materialsTotal))")>=0,'materials subtotal mode boundary missing')});
test('optional tool and consumables charge is explicit and bounded to service price',function(){['toolFeeEnabled','toolFeePct','Tool / consumables charge','% of service / labor','toolCharge'].forEach(function(x){ok(src.indexOf(x)>=0,x+' tool charge contract missing')});ok(src.indexOf("Math.max(0,n(c.price))*Math.max(0,n(c.toolFeePct))/100")>=0,'tool fee basis is not service/labor price')});
test('mini invoice includes service materials tool and total',function(){['Mini invoice','Service / labor','Materials','Mini invoice total','invoiceTotal'].forEach(function(x){ok(src.indexOf(x)>=0,x+' mini invoice content missing')});ok(src.indexOf('Math.max(0,n(c&&c.price))+materialsSubtotal(c)+toolCharge(c)')>=0,'invoice total does not sum service materials and tool')});
test('legacy calls remain backward compatible with zero material and tool defaults',function(){ok(src.indexOf("if(!c.materialsMode)c.materialsMode=c.materialItems.length?'itemized':'quick'")>=0,'legacy materials mode normalization missing');ok(src.indexOf('if(c.materialsTotal==null)c.materialsTotal=0')>=0,'legacy materials total normalization missing');ok(src.indexOf('if(c.toolFeeEnabled==null)c.toolFeeEnabled=false')>=0,'legacy tool toggle normalization missing')});
test('helper costs iterate every date in selected period including zero-call days',function(){ok(src.indexOf('eachDate(r[0],r[1]')>=0,'period does not iterate calendar dates');ok(src.indexOf('helperCostForDate(h,s,day)')>=0,'helper daily cost not evaluated independently of calls')});
test('helper economics are versioned by effective date',function(){['revisions','revisionFor','putRevision','Changes are versioned from the selected date','Disable from'].forEach(function(x){ok(src.indexOf(x)>=0,x+' missing')});ok(src.indexOf('data.helpers=data.helpers.filter')<0,'helper delete still erases historical economics')});
test('historical helper tax is revision-owned and ignores later global defaults',function(){ok(src.indexOf("var pct=r.taxEnabled!==false?Math.max(0,n(r.taxPct,0)):0")>=0,'helper tax is not revision-owned');ok(src.indexOf('s.helperTaxEnabled&&r.taxEnabled')<0,'current global helper tax toggle still gates history');ok(src.indexOf('n(r.taxPct,s.helperTaxPct)')<0,'current helper tax percentage still rewrites historical revisions');ok(src.indexOf('default helper tax estimate for new versions')>=0,'settings semantics do not describe default-only behavior');ok(src.indexOf('taxEnabled=r?r.taxEnabled!==false:settings.helperTaxEnabled')>=0,'new helper version does not inherit current default without touching existing revisions')});
test('completed calls snapshot applied owner tax',function(){ok(src.indexOf('taxPctApplied')>=0,'call tax snapshot missing');ok(src.indexOf("status==='completed'")>=0,'completed status snapshot boundary missing')});
test('obsolete global project mode loader is removed',function(){ok(reg.indexOf('electric-project-mode.js')<0,'old project mode selector still injected')});
global.BRUNO_TEST_RESULTS=out;
})();