'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};function test(n,f){out.total++;try{f();out.pass++;out.results.push({name:n,ok:true})}catch(e){out.fail++;out.results.push({name:n,ok:false,error:e.message})}}function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}function ok(v,m){if(!v)throw new Error(m||'assertion failed')}function throws(f,m){var h=false;try{f()}catch(e){h=true}ok(h,m||'expected throw')}
var A=global.BrunoElectricalTaskAdvanced;function input(o){var x={loadAmps:'20',voltage:'240',phase:'1',distanceFt:'50',material:'Cu',installation:'EMT',conductorType:'THHN_THWN2',loadBasis:'NONCONTINUOUS',vdTargetPct:'3',ambientC:'30',ccc:'2',terminalRating:'75',parallelAllowed:false,maxConductorSize:'',racewayStrategy:'SEPARATE_SETS'};Object.keys(o||{}).forEach(function(k){x[k]=o[k]});return x}function ground(o){var x={ocpdAmps:'20',neutralMode:'NONE',egcMaterial:'Cu'};Object.keys(o||{}).forEach(function(k){x[k]=o[k]});return x}
test('Stage 7A Branch Circuit shared chain',function(){is(A.calculate('BRANCH_CIRCUIT_RUN',input(),ground()).status,'PASS')});test('Branch missing current fails closed',function(){throws(function(){A.calculate('BRANCH_CIRCUIT_RUN',input({loadAmps:''}),ground())})});test('Branch missing grounding facts fails closed',function(){throws(function(){A.calculate('BRANCH_CIRCUIT_RUN',input(),ground({ocpdAmps:'',neutralMode:'UNRESOLVED'}))})});
test('Stage 7B EVSE explicit continuous basis',function(){throws(function(){A.calculate('EVSE_CIRCUIT',input(),ground())});is(A.calculate('EVSE_CIRCUIT',input({loadBasis:'CONTINUOUS'}),ground()).status,'PASS')});test('EVSE missing current fails closed',function(){throws(function(){A.calculate('EVSE_CIRCUIT',input({loadBasis:'CONTINUOUS',loadAmps:''}),ground())})});
test('Stage 7C HVAC explicit equipment facts',function(){is(A.calculate('HVAC_CIRCUIT',input({loadAmps:'32'}),ground({ocpdAmps:'40'})).status,'PASS')});test('HVAC missing current fails closed',function(){throws(function(){A.calculate('HVAC_CIRCUIT',input({loadAmps:''}),ground({ocpdAmps:'40'}))})});test('HVAC missing OCPD fails closed',function(){throws(function(){A.calculate('HVAC_CIRCUIT',input({loadAmps:'32'}),ground({ocpdAmps:''}))})});
test('Stage 7D Motor avoids second multiplier',function(){throws(function(){A.calculate('MOTOR_CIRCUIT',input({loadBasis:'CONTINUOUS'}),ground())});is(A.calculate('MOTOR_CIRCUIT',input(),ground()).status,'PASS')});test('Motor missing current fails closed',function(){throws(function(){A.calculate('MOTOR_CIRCUIT',input({loadAmps:''}),ground())})});test('Motor missing OCPD fails closed',function(){throws(function(){A.calculate('MOTOR_CIRCUIT',input(),ground({ocpdAmps:''}))})});
test('Stage 7E Transformer avoids second multiplier',function(){throws(function(){A.calculate('TRANSFORMER_FEED',input({loadBasis:'CONTINUOUS'}),ground())});is(A.calculate('TRANSFORMER_FEED',input({loadAmps:'125',voltage:'480',phase:'3'}),ground({ocpdAmps:'150'})).status,'PASS')});test('Transformer missing current fails closed',function(){throws(function(){A.calculate('TRANSFORMER_FEED',input({loadAmps:''}),ground())})});test('Transformer missing OCPD fails closed',function(){throws(function(){A.calculate('TRANSFORMER_FEED',input(),ground({ocpdAmps:''}))})});
test('Stage 7F Generator avoids second multiplier',function(){throws(function(){A.calculate('GENERATOR_FEEDER',input({loadBasis:'CONTINUOUS'}),ground())});is(A.calculate('GENERATOR_FEEDER',input({loadAmps:'100'}),ground({ocpdAmps:'125'})).status,'PASS')});test('Generator missing current fails closed',function(){throws(function(){A.calculate('GENERATOR_FEEDER',input({loadAmps:''}),ground())})});test('Generator missing OCPD fails closed',function(){throws(function(){A.calculate('GENERATOR_FEEDER',input(),ground({ocpdAmps:''}))})});
test('Stage 7G Generic Long Run preserves ampacity plus voltage-drop review semantics',function(){var r=A.calculate('LONG_DISTANCE_VD',input({loadAmps:'30',distanceFt:'1000',loadBasis:'NONCONTINUOUS',parallelAllowed:true}),ground({ocpdAmps:'30'}));ok(['PASS','NO SUPPORTED CONFIGURATION','REVIEW REQUIRED'].indexOf(r.status)>=0,'unexpected long-run status '+r.status);ok((r.warnings||[]).some(function(x){return x.indexOf('Generic Long Run uses the shared deterministic ampacity')>=0}),'long-run scope warning missing');is(r.taskTemplateEngineVersion,'electrical-task-advanced-v7')});
test('Generic Long Run requires explicit load basis',function(){throws(function(){A.calculate('LONG_DISTANCE_VD',input({loadBasis:''}),ground())})});test('Generic Long Run missing current fails closed',function(){throws(function(){A.calculate('LONG_DISTANCE_VD',input({loadAmps:''}),ground())})});test('Generic Long Run missing distance fails closed',function(){throws(function(){A.calculate('LONG_DISTANCE_VD',input({distanceFt:''}),ground())})});global.BRUNO_TEST_RESULTS=out;
})();
