'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function near(a,b,t){if(Math.abs(a-b)>(t||0.001))throw new Error('expected '+b+' ± '+(t||0.001)+', got '+a)}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function throws(fn,m){var hit=false;try{fn()}catch(e){hit=true}ok(hit,m||'expected throw')}
var T=global.BrunoElectricalTaskMaterialTakeoff,C=global.BrunoElectricalCatalogV1;
function base(o){var x={loadAmps:'300',voltage:'480',phase:'3',distanceFt:'50',material:'Cu',installation:'EMT',conductorType:'THHN_THWN2',loadBasis:'NONCONTINUOUS',vdTargetPct:'3',ambientC:'30',ccc:'3',terminalRating:'75',parallelAllowed:false,maxConductorSize:'',racewayStrategy:'SEPARATE_SETS'};Object.keys(o||{}).forEach(function(k){x[k]=o[k]});return x}
function ground(o){var x={ocpdAmps:'300',egcMaterial:'Cu',neutralMode:'NONE'};Object.keys(o||{}).forEach(function(k){x[k]=o[k]});return x}
function meta(){return{id:'task-1',revision:2,sourceEdition:'2026',jurisdiction:'Texas'}}
function seed(id,yourCost,customer){var r=C.items.find(function(x){return x.id===id});if(!r)throw new Error('seed missing '+id);var c=JSON.parse(JSON.stringify(r));c.yourCost=yourCost;c.unitCost=customer==null?0:customer;return c}
function job(catalog){localStorage.setItem('bruno-electric-v1',JSON.stringify({id:'job-a',catalog:catalog||[],materialsUsed:[],materialsUnresolved:[]}))}

test('Stage 5 short feeder creates calculated phase EGC and raceway lines',function(){job([]);var p=T.build(base(),ground(),meta(),{});is(p.status,'PASS');is(p.applyAllowed,true);var phase=p.lines.find(function(x){return x.id==='phase-calculated'}),egc=p.lines.find(function(x){return x.id==='egc-calculated'}),race=p.lines.find(function(x){return x.id==='raceway-calculated'});is(phase.qty,150);is(phase.catalogId,'ecat-thhn-cu-350');is(egc.qty,50);is(egc.catalogId,'ecat-thhn-cu-4');is(race.qty,50);is(race.catalogId,'ecat-emt-250');is(p.lines.filter(function(x){return x.classification==='FIELD_VERIFY'}).length,4)});
test('full-size neutral produces a separately classified neutral footage line',function(){job([]);var p=T.build(base(),ground({neutralMode:'FULL_SIZE'}),meta(),{}),n=p.lines.find(function(x){return x.id==='neutral-calculated'});ok(n,'neutral line missing');is(n.kind,'NEUTRAL');is(n.qty,50);is(n.catalogId,'ecat-thhn-cu-350')});
test('bounded allowances remain separate from calculated quantities',function(){job([]);var p=T.build(base(),ground(),meta(),{conductorAllowancePct:'10',racewayAllowancePct:'10'});is(p.status,'PASS');near(p.lines.find(function(x){return x.id==='phase-allowance'}).qty,15);near(p.lines.find(function(x){return x.id==='egc-allowance'}).qty,5);near(p.lines.find(function(x){return x.id==='raceway-allowance'}).qty,5);is(p.lines.find(function(x){return x.id==='phase-allowance'}).classification,'ALLOWANCE')});
test('allowance percent outside 0 to 20 fails closed',function(){job([]);throws(function(){T.build(base(),ground(),meta(),{conductorAllowancePct:'21'})});throws(function(){T.build(base(),ground(),meta(),{racewayAllowancePct:'-1'})})});
test('Stage 4 review-required long run cannot publish/apply final material takeoff',function(){job([]);var p=T.build(base({distanceFt:'1500',parallelAllowed:true}),ground(),meta(),{});is(p.status,'REVIEW REQUIRED');is(p.lines.length,0);is(p.applyAllowed,false);throws(function(){T.apply(p)})});
test('unsaved task can preview plan but apply remains blocked',function(){job([]);var p=T.build(base(),ground(),{},{});is(p.status,'PASS');is(p.applyAllowed,false);throws(function(){T.apply(p)})});
test('strict apply keeps blank Your Cost unresolved and never substitutes Customer Price',function(){job([seed('ecat-thhn-cu-350','',9.5),seed('ecat-thhn-cu-4','0',4.5),seed('ecat-emt-250','',22)]);var p=T.build(base(),ground(),meta(),{}),a=T.apply(p),j=a.job;var phase=j.materialsUnresolved.find(function(x){return x.sourceTakeoffLineId==='phase-calculated'});var egc=j.materialsUsed.find(function(x){return x.sourceTakeoffLineId==='egc-calculated'});var race=j.materialsUnresolved.find(function(x){return x.sourceTakeoffLineId==='raceway-calculated'});ok(phase&&race,'blank Your Cost lines not unresolved');is(phase.unitCost,null);is(phase.customerUnitPrice,9.5);is(phase.costState,'UNRESOLVED');is(egc.unitCost,0);is(egc.costState,'RESOLVED');is(race.unitCost,null)});
test('positive Your Cost creates resolved historical snapshot with task provenance',function(){job([seed('ecat-thhn-cu-350','2.75',9.5),seed('ecat-thhn-cu-4','1.1',4.5),seed('ecat-emt-250','3.2',22)]);var p=T.build(base(),ground(),meta(),{}),a=T.apply(p),phase=a.job.materialsUsed.find(function(x){return x.sourceTakeoffLineId==='phase-calculated'});is(phase.unitCost,2.75);is(phase.customerUnitPrice,9.5);is(phase.sourceTaskId,'task-1');is(phase.sourceTaskRevision,2);is(phase.sourceCodeEdition,'2026');is(phase.takeoffClassification,'CALCULATED')});
test('field-verify items are never converted into invented Job quantities',function(){job([seed('ecat-thhn-cu-350','2',9),seed('ecat-thhn-cu-4','1',4),seed('ecat-emt-250','3',20)]);var p=T.build(base(),ground(),meta(),{}),a=T.apply(p);is(a.added.some(function(x){return x.takeoffClassification==='FIELD_VERIFY'}),false)});
test('re-applying same task revision is idempotent',function(){job([seed('ecat-thhn-cu-350','2',9),seed('ecat-thhn-cu-4','1',4),seed('ecat-emt-250','3',20)]);var p=T.build(base(),ground(),meta(),{}),a=T.apply(p),b=T.apply(p);is(a.added.length,3);is(b.added.length,0);is(b.skipped.length,3)});
global.BRUNO_TEST_RESULTS=out;
})();