'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function throws(fn,m){var hit=false;try{fn()}catch(e){hit=true}ok(hit,m||'expected throw')}
var M=global.BrunoElectricalTaskMaterials,T=global.BrunoElectricalTaskTakeoff,API=global.BrunoElectricalTasks;
function seedJob(){localStorage.clear();localStorage.setItem('bruno-electric-v1',JSON.stringify({id:'job-stage5',catalog:[],materialsUsed:[],materialsUnresolved:[]}))}
function input(){return{loadAmps:'300',voltage:'480',phase:'3',distanceFt:'50',material:'Cu',installation:'EMT',conductorType:'THHN_THWN2',loadBasis:'NONCONTINUOUS',vdTargetPct:'3',ambientC:'30',ccc:'3',terminalRating:'75',parallelAllowed:false,maxConductorSize:'',racewayStrategy:'SEPARATE_SETS',ocpdAmps:'300',neutralMode:'NONE',egcMaterial:'Cu'}}
function calcInput(x){return{loadAmps:x.loadAmps,voltage:x.voltage,phase:x.phase,distanceFt:x.distanceFt,material:x.material,installation:x.installation,conductorType:x.conductorType,loadBasis:x.loadBasis,vdTargetPct:x.vdTargetPct,ambientC:x.ambientC,ccc:x.ccc,terminalRating:x.terminalRating,parallelAllowed:x.parallelAllowed,maxConductorSize:x.maxConductorSize,racewayStrategy:x.racewayStrategy}}
function ground(x){return{ocpdAmps:x.ocpdAmps,neutralMode:x.neutralMode,egcMaterial:x.egcMaterial}}
function savedTask(){var x=input(),d=API.create('FEEDER_PANEL_RUN',{name:'Stage5',inputs:x});d.inputs=x;return API.save(d)}
function take(x){return T.calculate(calcInput(x),ground(x))}

test('Add to Job requires a saved current task revision',function(){seedJob();var x=input(),r=take(x);throws(function(){M.apply(r,{id:'fake',revision:1,inputs:x},x)})});
test('unsaved form edits block material application',function(){seedJob();var s=savedTask(),x=input(),r=take(x),changed=JSON.parse(JSON.stringify(x));changed.distanceFt='55';throws(function(){M.apply(r,s,changed)},'changed draft should block apply')});
test('missing catalog definitions are created with unresolved Your Cost, never fake contractor cost',function(){seedJob();var s=savedTask(),x=input(),r=take(x),a=M.apply(r,s,x),j=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(a.added.length,0);is(a.unresolved.length,3);is(j.materialsUsed.length,0);is(j.materialsUnresolved.length,3);is(j.catalog.length,3);j.catalog.forEach(function(c){is(c.yourCost,'');is(c.priceStatus,'PLACEHOLDER')});j.materialsUnresolved.forEach(function(m){is(m.unitCost,null);is(m.costState,'UNRESOLVED');is(m.unresolvedReason,'YOUR_COST_UNRESOLVED');ok(m.catalogMatchId);ok(m.sourceTaskId===s.id)})});
test('Customer Price never substitutes for Your Cost',function(){seedJob();var s=savedTask(),x=input(),r=take(x);M.apply(r,s,x);var j=JSON.parse(localStorage.getItem('bruno-electric-v1'));j.catalog.forEach(function(c){c.unitCost=999;c.yourCost=''});j.materialsUnresolved=[];localStorage.setItem('bruno-electric-v1',JSON.stringify(j));M.apply(r,s,x);j=JSON.parse(localStorage.getItem('bruno-electric-v1'));var newer=j.materialsUnresolved.slice(-3);newer.forEach(function(m){is(m.unitCost,null);is(m.customerUnitPrice,999)})});
test('explicit zero Your Cost is resolved numeric zero',function(){seedJob();var s=savedTask(),x=input(),r=take(x);M.apply(r,s,x);var j=JSON.parse(localStorage.getItem('bruno-electric-v1'));j.materialsUnresolved=[];j.catalog.forEach(function(c){c.yourCost=0});localStorage.setItem('bruno-electric-v1',JSON.stringify(j));var a=M.apply(r,s,x);is(a.added.length,3);is(a.unresolved.length,0);a.added.forEach(function(m){is(m.unitCost,0);is(m.costState,'RESOLVED')})});
test('positive Your Cost is snapshotted and later Catalog edit does not rewrite history',function(){seedJob();var s=savedTask(),x=input(),r=take(x);M.apply(r,s,x);var j=JSON.parse(localStorage.getItem('bruno-electric-v1'));j.materialsUnresolved=[];j.catalog.forEach(function(c,i){c.yourCost=1.25+i});localStorage.setItem('bruno-electric-v1',JSON.stringify(j));var a=M.apply(r,s,x),first=a.added[0],old=first.unitCost;j=JSON.parse(localStorage.getItem('bruno-electric-v1'));var cat=j.catalog.find(function(c){return c.id===first.catalogMatchId});cat.yourCost=88;localStorage.setItem('bruno-electric-v1',JSON.stringify(j));j=JSON.parse(localStorage.getItem('bruno-electric-v1'));var hist=j.materialsUsed.find(function(m){return m.sourceTakeoffBatchId===a.batchId&&m.catalogMatchId===first.catalogMatchId});is(hist.unitCost,old);ok(hist.unitCost!==88)});
test('takeoff batch provenance is recorded',function(){seedJob();var s=savedTask(),x=input(),r=take(x);var a=M.apply(r,s,x),j=JSON.parse(localStorage.getItem('bruno-electric-v1')),b=j.electricalTaskMaterialBatches[0];is(b.id,a.batchId);is(b.sourceTaskId,s.id);is(b.sourceTaskRevision,s.revision);is(b.rowCount,3);is(b.unresolvedCount,3)});
test('ALLOWANCE and FIELD_VERIFY rows never enter numeric Job Materials automatically',function(){seedJob();var s=savedTask(),x=input(),r=take(x);M.apply(r,s,x);var j=JSON.parse(localStorage.getItem('bruno-electric-v1')),all=j.materialsUsed.concat(j.materialsUnresolved);is(all.length,r.rows.length);ok(all.every(function(m){return m.sourceBasis==='CALCULATED'}))});
global.BRUNO_TEST_RESULTS=out;
})();
