'use strict';
(function(){
var fs=require('fs'),path=require('path');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
var ui=fs.readFileSync(path.join(__dirname,'..','electrical-tasks-ui.js'),'utf8'),core=fs.readFileSync(path.join(__dirname,'..','electric-electrical-tasks.js'),'utf8'),stage5=fs.readFileSync(path.join(__dirname,'..','electrical-tasks-stage5-ui.js'),'utf8');
test('Electrical Tasks is a first-class tool workspace',function(){ok(ui.indexOf("dataset.tool='tasks'")>=0,'tasks nav missing');ok(ui.indexOf('Electrical Tasks / Field Calculator')>=0,'workspace title missing');ok(ui.indexOf("s.id='tool-tasks'")>=0,'tool section id missing')});
test('Stage 1 shows Feeder Panel form and future template inventory',function(){['Feeder / Panel Run','Branch Circuit Run','Long-Distance Voltage Drop','Conduit / Raceway Sizing','Transformer Feed','Motor Circuit','EVSE Circuit','HVAC Circuit','Generator / Feeder','Generic Custom Electrical Task'].forEach(function(x){ok(core.indexOf(x)>=0,x+' template missing')});ok(core.indexOf("enabled:true")>=0,'enabled feeder missing');ok(core.indexOf("enabled:false")>=0,'planned lock missing')});
test('Stage 1 makes Save and Job-scoped archive discoverable',function(){ok(ui.indexOf('Save Task Draft')>=0,'save action missing');ok(ui.indexOf('Saved on this Job')>=0,'saved list missing');ok(ui.indexOf('Duplicate')>=0,'duplicate missing');ok(ui.indexOf('Delete')>=0,'delete missing')});
test('Stage 1 explicitly refuses fabricated compliance calculations',function(){ok(ui.indexOf('No compliance answer')>=0||ui.indexOf('NO compliance answer')>=0,'no-fabrication boundary missing');ok(ui.indexOf('wire size')>=0,'wire boundary missing');ok(ui.indexOf('conduit size')>=0,'raceway boundary missing')});
test('Electrical Tasks UI preserves phone tablet desktop responsive contracts',function(){ok(ui.indexOf('@media(max-width:900px)')>=0,'tablet/compact breakpoint missing');ok(ui.indexOf('@media(max-width:600px)')>=0,'phone breakpoint missing');ok(ui.indexOf('bottom:78px')>=0,'phone action/bottom-nav clearance missing')});
test('Electrical Tasks promotes itself out of generic Other picker group',function(){ok(ui.indexOf('option[value="tasks"]')>=0||ui.indexOf("option[value=\"tasks\"]")>=0,'picker task lookup missing');ok(ui.indexOf("label='Electrical Tasks'")>=0||ui.indexOf("label = 'Electrical Tasks'")>=0||ui.indexOf(".label='Electrical Tasks'")>=0,'dedicated picker group missing')});
test('Stage 1 core never writes Job Materials',function(){ok(core.indexOf('materialsUsed')<0,'task core touches materialsUsed');ok(core.indexOf('materialsUnresolved')<0,'task core touches materialsUnresolved');ok(core.indexOf("FIELD='electricalTasks'")>=0,'job task field missing')});
test('Stage 4 grounding fields are persisted through shared task form serialization',function(){['ocpdAmps','neutralMode','egcMaterial'].forEach(function(k){ok(core.indexOf(k)>=0,k+' core persistence missing');ok(ui.indexOf(k+':get(')>=0,k+' UI serialization missing')});ok(ui.indexOf("set('et-ocpd'")>=0,'OCPD hydration missing');ok(ui.indexOf("set('et-neutral-mode'")>=0,'neutral hydration missing');ok(ui.indexOf("set('et-egc-material'")>=0,'EGC material hydration missing')});
test('Stage 5 Apply revalidates live inputs and saved task revision after takeoff build',function(){ok(stage5.indexOf('currentPlanStillMatchesSavedTask')>=0,'stale-plan guard missing');ok(stage5.indexOf('sourceMeta(normalizedForm())')>=0,'live form is not revalidated at Apply');ok(stage5.indexOf('rebuild Material Takeoff before Apply')>=0,'stale-plan user block missing');ok(stage5.indexOf('Apply Calculated Materials to Job')>=0,'explicit Apply action missing')});
global.BRUNO_TEST_RESULTS=out;
})();
