'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};function test(n,f){out.total++;try{f();out.pass++;out.results.push({name:n,ok:true})}catch(e){out.fail++;out.results.push({name:n,ok:false,error:e.message})}}function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}function ok(v,m){if(!v)throw new Error(m||'assertion failed')}function throws(f,m){var h=false;try{f()}catch(e){h=true}ok(h,m||'expected throw')}
var API=global.BrunoElectricalTasks;function job(extra){var j={quote:{customer:'Test'},materialsUsed:[{item:'existing',qty:1,unitCost:5}],materialsUnresolved:[{item:'unknown'}],catalog:[]};Object.keys(extra||{}).forEach(function(k){j[k]=extra[k]});localStorage.setItem('bruno-electric-v1',JSON.stringify(j));return j}
test('Electrical Tasks requires saved Job',function(){localStorage.clear();throws(function(){API.create('FEEDER_PANEL_RUN',{})})});test('Blank and zero remain distinct',function(){job();var a=API.create('FEEDER_PANEL_RUN',{inputs:{loadAmps:'',distanceFt:'0'}});is(a.inputs.loadAmps,'');is(a.inputs.distanceFt,'0')});test('Save remains inside active Job without touching materials',function(){job({necEdition:'2026',jurisdiction:'Texas'});var before=JSON.parse(localStorage.getItem('bruno-electric-v1')),s=API.save(API.create('FEEDER_PANEL_RUN',{inputs:{loadAmps:'300'}})),after=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(after.electricalTasks[0].id,s.id);is(JSON.stringify(after.materialsUsed),JSON.stringify(before.materialsUsed));is(s.sourceEdition,'2026')});test('Edit increments revision',function(){var a=API.list()[0],id=a.id;a.name='edited';var b=API.save(a);is(b.id,id);is(b.revision,2)});test('Duplicate remains unsaved',function(){var a=API.list()[0],d=API.duplicate(a.id);ok(d.id!==a.id);ok(API.get(d.id)===null)});test('Delete clears active task',function(){var id=API.list()[0].id;API.setActive(id);API.remove(id);is(API.list().length,0)});
test('Job A and B remain isolated',function(){job({quote:{customer:'A'}});var a=API.save(API.create('FEEDER_PANEL_RUN',{name:'A',inputs:{loadAmps:'100'}})),state=localStorage.getItem('bruno-electric-v1');job({quote:{customer:'B'}});is(API.list().length,0);API.save(API.create('FEEDER_PANEL_RUN',{name:'B',inputs:{loadAmps:'200'}}));localStorage.setItem('bruno-electric-v1',state);is(API.list()[0].id,a.id)});
[['BRANCH_CIRCUIT_RUN','20','NONCONTINUOUS'],['EVSE_CIRCUIT','48','CONTINUOUS'],['HVAC_CIRCUIT','32','NONCONTINUOUS'],['MOTOR_CIRCUIT','35','NONCONTINUOUS'],['TRANSFORMER_FEED','125','NONCONTINUOUS'],['GENERATOR_FEEDER','100','NONCONTINUOUS']].forEach(function(v){test('Enabled task persists '+v[0],function(){job();var d=API.create(v[0],{inputs:{loadAmps:v[1],loadBasis:v[2],distanceFt:'50',ocpdAmps:v[1],taskSpecific:{basis:'explicit'}}}),s=API.save(d);is(s.taskType,v[0]);is(s.inputs.loadAmps,v[1]);is(s.inputs.taskSpecific.basis,'explicit')})});
test('Stage 7G enables Generic Long Run and preserves long-run inputs',function(){job();var d=API.create('LONG_DISTANCE_VD',{inputs:{loadAmps:'30',voltage:'240',phase:'1',distanceFt:'1000',loadBasis:'NONCONTINUOUS',vdTargetPct:'3',ocpdAmps:'30',taskSpecific:{basis:'explicit long run'}}});is(d.taskType,'LONG_DISTANCE_VD');is(d.inputs.distanceFt,'1000');var s=API.save(d);is(s.inputs.taskSpecific.basis,'explicit long run')});
test('Non-Stage7 templates remain locked',function(){job();['RACEWAY_SIZING','CONDUCTOR_SIZING','PARALLEL_CONDUCTORS','SERVICE_FEEDER','GENERIC_CUSTOM'].forEach(function(t){throws(function(){API.create(t,{})},t+' should remain locked')})});test('No device-global task registry',function(){ok(API._fields.tasks==='electricalTasks');ok(!localStorage.getItem('bruno-electrical-tasks-v1'))});global.BRUNO_TEST_RESULTS=out;
})();
