'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};function test(n,f){out.total++;try{f();out.pass++;out.results.push({name:n,ok:true})}catch(e){out.fail++;out.results.push({name:n,ok:false,error:e.message})}}function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
var S=global.BrunoElectricalTaskSolver;
test('Stage 8 example extracts current and distance but asks unresolved compliance facts',function(){var r=S.extract('I need a 300A panel 1500 ft from service.');is(r.known.loadAmps,'300');is(r.known.distanceFt,'1500');['voltage','phase','material','installation','loadBasis','vdTargetPct'].forEach(function(k){ok(r.unresolved.indexOf(k)>=0,k+' should remain unresolved')});ok(!r.complete)});
test('Solver extracts only explicit supported electrical facts',function(){var r=S.extract('Run 80 amps at 480 V three phase, copper THHN in EMT, 220 feet, non-continuous, voltage drop target 3%.');is(r.known.loadAmps,'80');is(r.known.voltage,'480');is(r.known.phase,'3');is(r.known.material,'Cu');is(r.known.installation,'EMT');is(r.known.distanceFt,'220');is(r.known.loadBasis,'NONCONTINUOUS');is(r.known.vdTargetPct,'3');is(r.unresolved.length,0);ok(r.complete)});
test('Solver recognizes explicit aluminum and PVC variants',function(){var a=S.extract('40 amps 240 volts single phase aluminum in PVC schedule 40 100 feet continuous VD 2%');is(a.known.material,'Al');is(a.known.installation,'PVC_SCH40');is(a.known.phase,'1');var b=S.extract('40 A 240 V 1 phase Al PVC Sch. 80 100 ft continuous voltage drop: 2%');is(b.known.installation,'PVC_SCH80')});
test('Ambiguous prose does not infer aluminum from panel or compliance facts',function(){var r=S.extract('Install a panel near the barn.');ok(!Object.prototype.hasOwnProperty.call(r.known,'material'));ok(!Object.prototype.hasOwnProperty.call(r.known,'loadBasis'));ok(!Object.prototype.hasOwnProperty.call(r.known,'voltage'))});
test('Blank and explicit zero remain distinct in solver extraction',function(){var blank=S.extract('');ok(blank.unresolved.indexOf('loadAmps')>=0);var zero=S.extract('0 A at 240 V single phase, 0 ft, copper EMT noncontinuous, VD 3%');is(zero.known.loadAmps,'0');is(zero.known.distanceFt,'0')});
test('Bare percentages are not guessed as voltage-drop target',function(){var r=S.extract('30 A 240 V 1 phase copper EMT 100 ft noncontinuous with 3% tax');ok(!Object.prototype.hasOwnProperty.call(r.known,'vdTargetPct'))});
test('Every required input exposes Why and basis metadata',function(){S.requiredFields.forEach(function(k){ok(S.why(k).length>20,'why missing '+k);ok(S._test.basis[k],'basis missing '+k)})});
test('Solver assumptions expose critical boundaries',function(){var a=S.assumptions().join(' | ');ok(a.indexOf('No compliance-critical fact is inferred')>=0);ok(a.indexOf('Raceway fill is not pulling feasibility')>=0);ok(a.indexOf('resistance-only K-method')>=0)});
test('Solver is pure and does not mutate active Job',function(){var before=JSON.stringify({quote:{total:123},electricalTasks:[{id:'existing'}],materialsUsed:[{item:'x'}]});localStorage.setItem('bruno-electric-v1',before);S.extract('300 A 480 V 3 phase copper EMT 1500 ft noncontinuous voltage drop 3%');is(localStorage.getItem('bruno-electric-v1'),before)});
test('Field map targets existing Electrical Tasks inputs only',function(){var m=S.fieldMap();is(m.loadAmps,'et-load');is(m.distanceFt,'et-distance');is(m.vdTargetPct,'et-vd');ok(!m.ocpdAmps,'solver must not auto-populate unsupported OCPD inference')});
global.BRUNO_TEST_RESULTS=out;
})();
