'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function near(a,b){if(Math.abs(Number(a)-Number(b))>1e-6)throw new Error('expected '+b+', got '+a)}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}
function makeStorage(seed){var store=seed||{};return{getItem:function(k){return Object.prototype.hasOwnProperty.call(store,k)?store[k]:null},setItem:function(k,v){store[k]=String(v)},removeItem:function(k){delete store[k]},key:function(i){return Object.keys(store)[i]||null},get length(){return Object.keys(store).length},_store:store}}
function load(seed){var storage=makeStorage(seed),sandbox={console:console,localStorage:storage,setTimeout:function(fn){fn()},globalThis:null};sandbox.globalThis=sandbox;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','electric-pricing-margins-semantics.js'),'utf8'),sandbox,{filename:'electric-pricing-margins-semantics.js'});return{M:sandbox.BrunoPricingMarginsSemantics,storage:storage}}

test('Pricing & Margins blank Your Cost is first-class unresolved, never Customer Price or zero',function(){var x=load(),d=x.M.deriveRow({unitCost:100,yourCost:''});is(d.yourCostKnown,false);is(d.yourCost,null);is(d.grossDifference,null);is(d.marginPct,null);is(d.status,'UNRESOLVED')});
test('Pricing & Margins explicit zero is known zero with real 100 percent margin',function(){var x=load(),d=x.M.deriveRow({unitCost:100,yourCost:0});is(d.yourCostKnown,true);is(d.yourCost,0);near(d.grossDifference,100);near(d.marginPct,100);is(d.status,'RESOLVED')});
test('Pricing & Margins aggregate excludes unresolved rows from contractor cost profit margin math',function(){var x=load(),a=x.M.aggregate([{unitCost:100,yourCost:''},{unitCost:200,yourCost:120},{unitCost:50,yourCost:0}]);near(a.customerTotal,350);near(a.resolvedCustomerTotal,250);near(a.resolvedCostTotal,120);near(a.resolvedGrossDifference,130);near(a.resolvedMarginPct,52);is(a.unresolvedCount,1);is(a.resolvedCount,2)});
test('known cost -> blank persists unresolved across saved job and removes stale cost-map overrides',function(){var seed={'bruno-electric-v1':JSON.stringify({catalog:[{id:'c1',unitCost:100,yourCost:60}]}),'bruno-electric-catalog-costs-v1':JSON.stringify({c1:60}),'bruno-job-catalog-costs-v1':JSON.stringify({c1:61})},x=load(seed);x.M.persistYourCost('c1','');var job=JSON.parse(x.storage.getItem('bruno-electric-v1')),m1=JSON.parse(x.storage.getItem('bruno-electric-catalog-costs-v1')),m2=JSON.parse(x.storage.getItem('bruno-job-catalog-costs-v1'));is(job.catalog[0].yourCost,'');ok(!Object.prototype.hasOwnProperty.call(m1,'c1'),'primary stale cost survived');ok(!Object.prototype.hasOwnProperty.call(m2,'c1'),'secondary stale cost survived');is(x.M.deriveRow(job.catalog[0]).status,'UNRESOLVED')});
test('blank -> explicit zero persists known zero and primary map zero without coercion ambiguity',function(){var seed={'bruno-electric-v1':JSON.stringify({catalog:[{id:'c1',unitCost:100,yourCost:''}]})},x=load(seed);x.M.persistYourCost('c1','0');var job=JSON.parse(x.storage.getItem('bruno-electric-v1')),m=JSON.parse(x.storage.getItem('bruno-electric-catalog-costs-v1'));is(job.catalog[0].yourCost,0);is(m.c1,0);is(x.M.deriveRow(job.catalog[0]).status,'RESOLVED')});
test('explicit zero -> blank returns to unresolved and removes persisted zero map',function(){var seed={'bruno-electric-v1':JSON.stringify({catalog:[{id:'c1',unitCost:100,yourCost:0}]}),'bruno-electric-catalog-costs-v1':JSON.stringify({c1:0})},x=load(seed);x.M.persistYourCost('c1','');var job=JSON.parse(x.storage.getItem('bruno-electric-v1')),m=JSON.parse(x.storage.getItem('bruno-electric-catalog-costs-v1'));is(job.catalog[0].yourCost,'');ok(!Object.prototype.hasOwnProperty.call(m,'c1'),'zero map survived blank transition');is(x.M.deriveRow(job.catalog[0]).status,'UNRESOLVED')});
test('blank discount input remains unresolved; explicit discount resolves deterministic Your Cost',function(){var seed={'bruno-electric-v1':JSON.stringify({catalog:[{id:'c1',unitCost:100,yourCost:''}]})},x=load(seed);x.M.persistDiscount('c1','');var job=JSON.parse(x.storage.getItem('bruno-electric-v1'));is(job.catalog[0].yourCost,'');x.M.persistDiscount('c1','25');job=JSON.parse(x.storage.getItem('bruno-electric-v1'));near(job.catalog[0].yourCost,75);is(x.M.deriveRow(job.catalog[0]).status,'RESOLVED')});
test('save-reload sequence preserves blank -> zero -> blank semantic boundary',function(){var seed={'bruno-electric-v1':JSON.stringify({catalog:[{id:'c1',unitCost:125,yourCost:''}]})},x=load(seed);x.M.persistYourCost('c1','');var persisted=x.storage._store;x=load(persisted);var job=JSON.parse(x.storage.getItem('bruno-electric-v1'));is(x.M.deriveRow(job.catalog[0]).status,'UNRESOLVED');x.M.persistYourCost('c1','0');persisted=x.storage._store;x=load(persisted);job=JSON.parse(x.storage.getItem('bruno-electric-v1'));is(job.catalog[0].yourCost,0);is(x.M.deriveRow(job.catalog[0]).status,'RESOLVED');x.M.persistYourCost('c1','');persisted=x.storage._store;x=load(persisted);job=JSON.parse(x.storage.getItem('bruno-electric-v1'));is(job.catalog[0].yourCost,'');is(x.M.deriveRow(job.catalog[0]).status,'UNRESOLVED')});
test('strict runtime renders unresolved labels and owns a dedicated margins body',function(){var src=fs.readFileSync(path.join(__dirname,'..','electric-pricing-margins-semantics.js'),'utf8');ok(src.indexOf('margins-body-strict')>=0,'strict tbody missing');ok(src.indexOf('Unresolved')>=0,'unresolved UI label missing');ok(src.indexOf('strict-v2')>=0,'strict runtime version missing')});
test('bootstrap removes legacy margins and starts canonical hydration immediately',function(){var src=fs.readFileSync(path.join(__dirname,'..','sw-register.js'),'utf8');var fn=src.indexOf('function prepareStrictMarginsRuntime'),firstCall=src.indexOf('prepareStrictMarginsRuntime();',fn+1),loadCall=src.lastIndexOf('loadAppNavigation();');ok(fn>=0,'prepareStrictMarginsRuntime missing');ok(src.indexOf("document.getElementById('margins-body')")>=0,'legacy tbody lookup missing');ok(src.indexOf("strict.id='margins-body-strict'")>=0,'strict tbody creation missing');ok(src.indexOf('removeChild(legacy)')>=0,'legacy tbody not removed');ok(firstCall>=0&&loadCall>=0&&firstCall<loadCall,'strict takeover must precede canonical UI hydration');ok(src.indexOf("document.addEventListener('DOMContentLoaded',loadAppNavigation")<0,'canonical navigation is still delayed until DOMContentLoaded');ok(src.indexOf('data-legacy-margins-disabled')>=0,'legacy-disabled marker missing')});

global.BRUNO_TEST_RESULTS=out;
})();