'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
var src=fs.readFileSync(path.join(__dirname,'..','electric-quote-lifecycle.js'),'utf8');
function load(seed,recommended,co){var store={'bruno-electric-v1':JSON.stringify(seed||{})},timers=[],reloadCount=0,nodes={
 'q-total':{textContent:'$'+String(recommended==null?1000:recommended)},'chip-quote':{textContent:'$'+String(recommended==null?1000:recommended)},'q-cos':{textContent:'$'+String(co||0)},
 'q-job':{value:'J-1'},'q-proposal':{value:'P-1'},'q-customer':{value:'Customer A'},'q-date':{value:'2026-09-16'}
};var doc={readyState:'complete',getElementById:function(id){return nodes[id]||null},querySelector:function(){return null},createElement:function(){return{}},addEventListener:function(){}};var root={document:doc,localStorage:{getItem:function(k){return Object.prototype.hasOwnProperty.call(store,k)?store[k]:null},setItem:function(k,v){store[k]=String(v)}},location:{reload:function(){reloadCount++}},addEventListener:function(){},setTimeout:function(fn){timers.push(fn);return timers.length},clearTimeout:function(){},MutationObserver:null};var sb={window:root,globalThis:root,console:console,Date:Date,Math:Math,Number:Number,String:String,Array:Array,Object:Object,JSON:JSON};vm.runInNewContext(src,sb,{filename:'electric-quote-lifecycle.js'});return{M:root.BrunoQuoteLifecycle,nodes:nodes,store:store,timers:timers,job:function(){return JSON.parse(store['bruno-electric-v1'])},runLastTimer:function(){var fn=timers[timers.length-1];if(typeof fn==='function')fn()},reloads:function(){return reloadCount}}}
test('blank manual adjustment uses live recommended price',function(){var x=load({},1250);var c=x.M.candidate('');is(c.priceSource,'LIVE_RECOMMENDED');is(c.customerAmount,1250);is(c.manualOverride,null)});
test('positive manual adjustment explicitly overrides live recommendation',function(){var x=load({},1250);var c=x.M.candidate('1400');is(c.priceSource,'MANUAL_ADJUSTMENT');is(c.customerAmount,1400);is(c.recommended,1250)});
test('explicit zero manual adjustment fails closed instead of becoming free quote',function(){var x=load({},1250),threw=false;try{x.M.candidate('0')}catch(e){threw=true}ok(threw,'zero manual override was accepted')});
test('approval snapshots amount cost completeness metadata and applied calculation provenance',function(){var seed={materialsUnresolved:[{item:'Unknown'}],residentialAppliedCalculation:{calculationId:'rl-1',name:'House',sourceVersion:'residential-apply-v1'},quote:{customer:'legacy'}};var x=load(seed,2300,200),a=x.M.approve('2500');is(a.customerAmount,2500);is(a.recommendedAtApproval,2300);is(a.approvedChangeOrdersAtApproval,200);is(a.costCompleteAtApproval,false);is(a.unresolvedMaterialCountAtApproval,1);is(a.appliedCalculationAtApproval.calculationId,'rl-1');is(a.quoteMeta.jobNumber,'J-1');is(a.revision,1)});
test('approval persists snapshot before scheduling workspace state synchronization',function(){var x=load({id:'job-1',quote:{jobNumber:'J-1'},materialsUnresolved:[]},1800),before=x.timers.length,a=x.M.approve('');is(x.job().quoteLifecycle.approved.approvalId,a.approvalId);is(x.timers.length,before+1);is(x.reloads(),0);x.runLastTimer();is(x.reloads(),1)});
test('post-approval live price and Job edits cannot mutate approved snapshot',function(){var x=load({materialsUnresolved:[]},1800);var a=x.M.approve('');x.nodes['q-total'].textContent='$9999';var j=x.job();j.materialsUnresolved=[{item:'Later unknown'}];x.store['bruno-electric-v1']=JSON.stringify(j);var persisted=x.M.approved();is(persisted.customerAmount,a.customerAmount);is(persisted.recommendedAtApproval,1800);is(persisted.costCompleteAtApproval,true)});
test('re-approval increments revision and preserves previous approval in history',function(){var x=load({},1000);var a=x.M.approve('');x.nodes['q-total'].textContent='$1200';var b=x.M.approve('');is(a.revision,1);is(b.revision,2);is(x.M.history().length,1);is(x.M.history()[0].approvalId,a.approvalId);is(x.M.history()[0].customerAmount,1000)});
test('invoice basis is sourced only from approved immutable quote snapshot',function(){var x=load({},1500),blocked=false;try{x.M.invoiceBasis()}catch(e){blocked=true}ok(blocked,'invoice basis existed before approval');var a=x.M.approve('1650');x.nodes['q-total'].textContent='$9000';var b=x.M.invoiceBasis();is(b.source,'APPROVED_QUOTE_SNAPSHOT');is(b.approvalId,a.approvalId);is(b.amount,1650);is(b.revision,1)});
test('lifecycle source explicitly labels live manual approved and invoice boundaries',function(){['LIVE RECOMMENDED','MANUAL ADJUSTED','APPROVED SNAPSHOT','Approved Quote Rev','immutable invoice basis'].forEach(function(s){ok(src.indexOf(s)>=0,'missing lifecycle label '+s)})});
test('approval implementation does not rewrite current quote recommendation after approval',function(){ok(src.indexOf('recommendedAtApproval')>=0,'recommended snapshot missing');ok(src.indexOf("source:'APPROVED_QUOTE_SNAPSHOT'")>=0,'invoice snapshot source missing');ok(src.indexOf('quoteLifecycle={version:VERSION,approved:snap,history:hist}')>=0,'persisted lifecycle missing')});
global.BRUNO_TEST_RESULTS=out;
})();
