'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
var H=global.BrunoResidentialLiveHistory,A=global.BrunoResidentialApplyJob;
function seed(cost){localStorage.clear();localStorage.setItem('bruno-electric-v1',JSON.stringify({materialsUsed:[{item:'Manual existing',qty:1,unitCost:9},{item:'Other generated',qty:1,unitCost:5,generatedBy:{source:'commercial-phase'}}],materialsUnresolved:[],catalog:[{id:'wire',item:'Wire',units:'FT',unitCost:10,yourCost:cost}]}))}
function snap(name,qty){return{name:name,inputs:{squareFeet:1000},summary:{totalCircuits:5,totalCableFt:500},bom:[{item:'Wire',qty:qty||10,unit:'FT',source:'Residential Live Engine'}],wireTakeoff:{mode:'quick',totalFt:9999,settings:{mode:'quick',wastePct:10,quickFtPerSqFt:9}}}}
test('saved Residential calculation does not mutate Job Materials before Apply',function(){seed(6);var before=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed;H.save(snap('Saved only',10));var after=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed;is(JSON.stringify(after),JSON.stringify(before))});
test('Apply uses saved BOM and persists provenance',function(){seed(6);var s=H.save(snap('Apply House',10)),tx=A.applyActive(),job=JSON.parse(localStorage.getItem('bruno-electric-v1')),row=job.materialsUsed.filter(function(x){return x.catalogMatchId==='wire'})[0];ok(row,'applied wire missing');is(row.qty,10);is(row.unitCost,6);is(row.costState,'RESOLVED');is(job.residentialAppliedCalculation.calculationId,s.id);is(job.residentialAppliedCalculation.name,'Apply House');ok(job.residentialAppliedCalculation.appliedAt,'applied timestamp missing');is(tx.provenance.sourceType,'RESIDENTIAL_LIVE_SAVED')});
test('Apply preserves manual and non-Residential generated rows',function(){seed(6);H.save(snap('Preserve House',10));A.applyActive();var rows=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed;ok(rows.some(function(x){return x.item==='Manual existing'}),'manual row lost');ok(rows.some(function(x){return x.item==='Other generated'}),'other-source row lost')});
test('blank Your Cost applies to unresolved store and not numeric materialsUsed',function(){seed('');H.save(snap('Blank Cost',10));A.applyActive();var job=JSON.parse(localStorage.getItem('bruno-electric-v1'));ok(!job.materialsUsed.some(function(x){return x.catalogMatchId==='wire'}),'unresolved row leaked into numeric materialsUsed');var u=job.materialsUnresolved.filter(function(x){return x.catalogMatchId==='wire'})[0];ok(u,'unresolved row missing');is(u.unitCost,null);is(u.costState,'UNRESOLVED');is(u.unresolvedReason,'YOUR_COST_UNRESOLVED')});
test('explicit zero Your Cost remains resolved numeric zero',function(){seed(0);H.save(snap('Zero Cost',10));A.applyActive();var row=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed.filter(function(x){return x.catalogMatchId==='wire'})[0];ok(row,'resolved zero row missing');is(row.unitCost,0);is(row.costState,'RESOLVED')});
test('re-Apply replaces prior Residential application only',function(){seed(6);var a=H.save(snap('Version A',10));A.applyActive();var b=H.save(snap('Version B',20));A.applyActive();var job=JSON.parse(localStorage.getItem('bruno-electric-v1')),res=job.materialsUsed.filter(function(x){return x.generatedBy&&String(x.generatedBy.source).indexOf(A.sourcePrefix+':')===0});is(res.length,1);is(res[0].qty,20);is(job.residentialAppliedCalculation.calculationId,b.id);ok(a.id!==b.id,'fixture did not create second archive identity');ok(job.materialsUsed.some(function(x){return x.item==='Manual existing'}),'manual row lost on reapply')});
test('Apply migrates legacy Residential generated rows without touching other sources',function(){seed(6);var job=JSON.parse(localStorage.getItem('bruno-electric-v1'));job.materialsUsed.push({item:'Legacy wire',qty:1,unitCost:1,generatedBy:{source:'residential-live-takeoff'}});localStorage.setItem('bruno-electric-v1',JSON.stringify(job));H.save(snap('Migration House',10));A.applyActive();job=JSON.parse(localStorage.getItem('bruno-electric-v1'));ok(!job.materialsUsed.some(function(x){return x.generatedBy&&x.generatedBy.source==='residential-live-takeoff'}),'legacy Residential row survived');ok(job.materialsUsed.some(function(x){return x.generatedBy&&x.generatedBy.source==='commercial-phase'}),'other source removed during migration')});
test('editing saved-active structure after Apply does not silently mutate Job until next Apply',function(){seed(6);H.save(snap('Stable Job',10));A.applyActive();var applied=JSON.parse(localStorage.getItem('bruno-electric-v1')).materialsUsed.filter(function(x){return x.catalogMatchId==='wire'})[0].qty;H.save(snap('Stable Job changed',30));var job=JSON.parse(localStorage.getItem('bruno-electric-v1'));var still=job.materialsUsed.filter(function(x){return x.catalogMatchId==='wire'})[0].qty;is(still,applied);ok(!A.isActiveApplied(),'new saved calculation incorrectly marked applied')});
test('quick wire budget metadata never substitutes saved BOM quantity during Apply',function(){seed(6);H.save(snap('Quick Budget Metadata',12));A.applyActive();var job=JSON.parse(localStorage.getItem('bruno-electric-v1')),row=job.materialsUsed.filter(function(x){return x.catalogMatchId==='wire'})[0];is(row.qty,12);ok(row.qty!==9999,'quick budget footage leaked into exact Job Material BOM')});
global.BRUNO_TEST_RESULTS=out;
})();
