'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
var H=global.BrunoResidentialLiveHistory;
function seed(price,cost){localStorage.clear();localStorage.setItem('bruno-electric-v1',JSON.stringify({materialsUsed:[{item:'Manual'}],catalog:[{id:'c1',item:'Wire',units:'FT',unitCost:price==null?10:price,yourCost:cost==null?6:cost}]}))}
function snap(name){return{name:name||'House A',inputs:{squareFeet:2100,overrides:{generalReceptacles:''},overrideProvenance:{generalReceptacles:'AUTO'}},summary:{totalCircuits:8,totalCableFt:1500},bom:[{item:'Wire',qty:10,unit:'FT'}],pricing:{customerMaterialTotal:1,yourMaterialCost:1}}}
function bomRows(){return[{item:'Wire',qty:10,unit:'FT',version:'residential-live-v2'}]}
test('confirmed residential calculation becomes active job estimate and archive entry',function(){seed(10,6);var s=H.save(snap('House A'));ok(s.id,'id missing');is(H.active().name,'House A');is(H.list().length,1);is(H.active().pricing.customerMaterialTotal,100);is(H.active().pricing.yourMaterialCost,60);var job=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(job.residentialLiveActive.id,s.id);ok(!Object.prototype.hasOwnProperty.call(job.residentialLiveActive,'pricing'),'stale pricing persisted in active snapshot')});
test('archive stores BOM not pricing and reprices from current Catalog',function(){seed(10,6);H.save(snap('Live Plan'));var raw=JSON.parse(localStorage.getItem('bruno-residential-live-library-v1'))[0];ok(Array.isArray(raw.bom)&&raw.bom.length===1,'BOM missing from archive');ok(!Object.prototype.hasOwnProperty.call(raw,'pricing'),'pricing snapshot persisted');var job=JSON.parse(localStorage.getItem('bruno-electric-v1'));job.catalog[0].unitCost=14;job.catalog[0].yourCost=8;localStorage.setItem('bruno-electric-v1',JSON.stringify(job));var r=H.list()[0];is(r.pricing.customerMaterialTotal,140);is(r.pricing.yourMaterialCost,80);is(r.pricingMode,'LIVE_CATALOG')});
test('override provenance survives save and duplicate',function(){seed();var a=H.save({name:'Plan',inputs:{squareFeet:1800,overrides:{generalReceptacles:'',lights:14},overrideProvenance:{generalReceptacles:'AUTO',lights:'USER'}},bom:[{item:'Wire',qty:5,unit:'FT'}]});is(H.active().inputs.overrideProvenance.generalReceptacles,'AUTO');is(H.active().inputs.overrideProvenance.lights,'USER');var d=H.duplicate(a.id);is(d.inputs.overrideProvenance.generalReceptacles,'AUTO');is(d.inputs.overrideProvenance.lights,'USER');is(d.inputs.overrides.generalReceptacles,'');is(d.inputs.overrides.lights,14)});
test('saving another confirmed calculation keeps archive and replaces active only',function(){seed();var a=H.save(snap('House A'));var b=H.save(snap('House B'));is(H.active().id,b.id);is(H.list().length,2);ok(H.list().some(function(x){return x.id===a.id}),'first archive snapshot lost')});
test('unchanged repeated save is idempotent and reuses active archive identity',function(){seed();var a=H.save(snap('Idempotent House')),count1=H.list().length,b=H.save(snap('Idempotent House'));is(b.id,a.id);is(H.list().length,count1);is(H.active().id,a.id)});
test('changed live calculation creates a new archive identity and leaves prior snapshot immutable',function(){seed();var a=H.save(snap('Versioned House')),before=JSON.stringify(H.list().filter(function(x){return x.id===a.id})[0]),changed=snap('Versioned House');changed.inputs.squareFeet=2400;changed.summary.totalCableFt=1800;var b=H.save(changed);ok(b.id!==a.id,'changed calculation reused old id');is(H.list().length,2);var old=H.list().filter(function(x){return x.id===a.id})[0];is(JSON.stringify(old),before)});
test('duplicate creates reusable editable copy without overwriting source',function(){seed();var a=H.save({name:'Builder Plan 1',inputs:{squareFeet:1800,overrides:{generalReceptacles:20},overrideProvenance:{generalReceptacles:'USER'}},bom:[{item:'Wire',qty:5,unit:'FT'}]});var d=H.duplicate(a.id);ok(d.id!==a.id,'duplicate reused id');is(d.inputs.squareFeet,1800);is(d.inputs.overrides.generalReceptacles,20);ok(d.name.indexOf('copy')>=0,'copy name missing');is(H.list().length,1);is(d.pricing.customerMaterialTotal,50)});
test('delete removes only selected archive item',function(){seed();var a=H.save(snap('Delete A')),b=H.save(snap('Delete B'));is(H.list().length,2);H.remove(a.id);var rows=H.list();is(rows.length,1);is(rows[0].id,b.id)});
test('legacy confirm entry point saves snapshot but does not mutate Job Materials',function(){seed();var before=JSON.parse(localStorage.getItem('bruno-electric-v1')),tx=H.confirmAtomic(snap('Save Only House'),'residential-live-takeoff',bomRows()),job=JSON.parse(localStorage.getItem('bruno-electric-v1'));is(tx.bomResult.saveOnly,true);is(tx.bomResult.added,0);ok(job.residentialLiveActive,'active snapshot missing');is(JSON.stringify(job.materialsUsed),JSON.stringify(before.materialsUsed));is(JSON.stringify(job.materialsUnresolved||[]),JSON.stringify(before.materialsUnresolved||[]));is(H.list().length,1)});
test('unchanged repeated save-only confirm does not create duplicate archive rows',function(){seed();var a=H.confirmAtomic(snap('Atomic Idempotent'),'residential-live-takeoff',bomRows()).saved,b=H.confirmAtomic(snap('Atomic Idempotent'),'residential-live-takeoff',bomRows()).saved;is(a.id,b.id);is(H.list().length,1)});
test('save transaction rolls job back when archive write fails',function(){seed();var beforeJob=localStorage.getItem('bruno-electric-v1'),beforeLib=localStorage.getItem('bruno-residential-live-library-v1'),orig=localStorage.setItem,calls=0;localStorage.setItem=function(k,v){calls++;if(calls===2)throw new Error('injected archive failure');return orig.call(localStorage,k,v)};var threw=false;try{H.confirmAtomic(snap('Fail House'),'residential-live-takeoff',bomRows())}catch(e){threw=true}finally{localStorage.setItem=orig}ok(threw,'injected failure did not escape');is(localStorage.getItem('bruno-electric-v1'),beforeJob);is(localStorage.getItem('bruno-residential-live-library-v1'),beforeLib)});
test('save transaction leaves both states unchanged when first job write fails',function(){seed();var beforeJob=localStorage.getItem('bruno-electric-v1'),beforeLib=localStorage.getItem('bruno-residential-live-library-v1'),orig=localStorage.setItem,calls=0;localStorage.setItem=function(k,v){calls++;if(calls===1)throw new Error('injected job failure');return orig.call(localStorage,k,v)};var threw=false;try{H.confirmAtomic(snap('Fail First'),'residential-live-takeoff',bomRows())}catch(e){threw=true}finally{localStorage.setItem=orig}ok(threw,'injected failure did not escape');is(localStorage.getItem('bruno-electric-v1'),beforeJob);is(localStorage.getItem('bruno-residential-live-library-v1'),beforeLib)});
test('archive survives active clear for reuse on another job workflow',function(){seed();H.save(snap('Reusable Plan'));H.clearActive();ok(!H.active(),'active not cleared');is(H.list().length,1)});
global.BRUNO_TEST_RESULTS=out;
})();
