'use strict';
(function(){
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,m){if(!v)throw new Error(m||'expected truthy')}
function throws(fn,msg){var threw=false;try{fn()}catch(e){threw=true}ok(threw,msg||'expected throw')}
function findBom(r,item){return r.bom.find(function(x){return x.item===item})}
var E=global.BrunoResidentialLive;
function base(){return{squareFeet:2000,bedrooms:3,bathrooms:1,powderRooms:1,livingRooms:1,diningRooms:1,offices:0,kitchens:1,laundryAreas:1,garageBays:2,outdoorGfci:2,generalCircuitAmps:20,receptaclesPerGeneralCircuit:5}}

test('live engine requires positive square footage',function(){throws(function(){E.calculate({squareFeet:0})},'zero square footage accepted')});
test('room-count-only run labels layout-driven minimums unresolved',function(){var r=E.calculate(base());ok(!r.codeMinimums.generalReceptacles.known,'general minimum falsely claimed from room count');ok(!r.codeMinimums.bathroomReceptacles.known,'bathroom minimum falsely claimed from room count');ok(!r.codeMinimums.kitchenReceptacles.known,'kitchen minimum falsely claimed from room count');is(r.status,'NO KNOWN CONFLICTS / LAYOUT REQUIRED')});
test('qualifying wall segments calculate independent 210.52A spacing minimum and retain nonqualifying numeric segments',function(){var x=E.wallMinimum('10,8,14,1');is(x.count,4);is(x.segments.length,3);is(x.nonqualifyingSegments.length,1);ok(x.reference.indexOf('210.52(A)')>=0)});
test('malformed wall segment token fails closed instead of partial minimum',function(){throws(function(){E.wallMinimum('13,abc,13')},'malformed wall segment silently accepted');throws(function(){E.calculate(Object.assign(base(),{qualifyingWallSegmentsFt:'13,,13'}))},'blank wall token silently accepted');throws(function(){E.calculate(Object.assign(base(),{qualifyingWallSegmentsFt:'13,-4,13'}))},'negative wall token silently accepted')});
test('valid numeric wall segments below 2ft are explicitly nonqualifying not malformed',function(){var x=E.wallMinimum('1,1.5,13');is(x.count,2);is(x.nonqualifyingSegments.length,2);ok(x.known,'complete numeric list should be known')});
test('wall-derived general minimum drives initial live design',function(){var x=base();x.qualifyingWallSegmentsFt='10,8,14';var r=E.calculate(x);is(r.codeMinimums.generalReceptacles.value,4);is(r.design.generalReceptacles,4);is(r.violations.length,0)});
test('below wall-derived general minimum is flagged non-compliant',function(){var x=base();x.qualifyingWallSegmentsFt='13,13';x.overrides={generalReceptacles:2};var r=E.calculate(x);is(r.codeMinimums.generalReceptacles.value,4);ok(r.violations.some(function(v){return v.key==='generalReceptacles'}),'general under-minimum not flagged');is(r.status,'NON-COMPLIANT')});
test('bathroom and powder device quantity remains layout required and room count is design allowance only',function(){var x=base();x.overrides={bathroomReceptacles:1};var r=E.calculate(x);ok(!r.codeMinimums.bathroomReceptacles.known,'bathroom numeric minimum asserted');is(r.codeMinimums.bathroomReceptacles.value,null);ok(!r.violations.some(function(v){return v.key==='bathroomReceptacles'}),'false bathroom non-compliance emitted');is(r.design.bathroomReceptacles,1)});
test('ambiguous powder toilet rooms alone do not create bathroom code circuit',function(){var x=base();x.bathrooms=0;x.powderRooms=2;var r=E.calculate(x);ok(!r.circuits.some(function(c){return c.label==='Bathroom receptacles'}),'powder/toilet room incorrectly forced bathroom circuit')});
test('adding receptacles can add general circuit and breaker automatically',function(){var x=base();x.overrides={generalReceptacles:5};var a=E.calculate(x);x.overrides={generalReceptacles:6};var b=E.calculate(x);is(a.summary.generalCircuits,1);is(b.summary.generalCircuits,2);is(findBom(a,'20A 1-pole breaker').qty+1,findBom(b,'20A 1-pole breaker').qty)});
test('adding receptacles automatically increases estimated cable and BOM devices',function(){var x=base();x.overrides={generalReceptacles:5};var a=E.calculate(x);x.overrides={generalReceptacles:10};var b=E.calculate(x);ok(b.summary.totalCableFt>a.summary.totalCableFt,'cable did not increase');is(findBom(a,'15A duplex receptacle').qty,5);is(findBom(b,'15A duplex receptacle').qty,10)});
test('switching general circuit 20A to 15A changes conductor and breaker family',function(){var x=base();x.overrides={generalReceptacles:6};x.generalCircuitAmps=20;var a=E.calculate(x);x.generalCircuitAmps=15;var b=E.calculate(x);ok(findBom(a,'12/2 NM-B with ground'),'20A general cable missing');ok(findBom(b,'14/2 NM-B with ground'),'15A general cable missing');ok(findBom(b,'15A 1-pole breaker'),'15A breaker missing')});
test('kitchen laundry confirmed bathroom and garage circuit requirements appear from room inputs',function(){var r=E.calculate(base());['Kitchen small-appliance','Bathroom receptacles','Laundry','Garage receptacles'].forEach(function(name){ok(r.circuits.some(function(c){return c.label===name}),name+' missing')})});
test('ordinary receptacle count changes branch takeoff but not floor-area service VA',function(){var x=base();x.overrides={generalReceptacles:5};var a=E.calculate(x);x.overrides={generalReceptacles:20};var b=E.calculate(x);is(a.summary.generalLoadVA,b.summary.generalLoadVA);ok(b.summary.totalCircuits>a.summary.totalCircuits,'branch circuits did not respond')});
test('live BOM includes panel-space-driving breakers wire devices staples and connectors',function(){var r=E.calculate(base());['20A 1-pole breaker','12/2 NM-B with ground','15A duplex receptacle','NM cable staple allowance','Small wire connector allowance'].forEach(function(item){ok(findBom(r,item),item+' missing')})});
global.BRUNO_TEST_RESULTS=out;
})();