'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,msg){if(!v)throw new Error(msg||'assertion failed')}
var source=fs.readFileSync(path.join(__dirname,'..','electric-residential-wire-takeoff.js'),'utf8');
function module(){var store={},w={BrunoResidentialLive:global.BrunoResidentialLive,BrunoResidentialLiveHistory:null,document:null,localStorage:{getItem:function(k){return Object.prototype.hasOwnProperty.call(store,k)?store[k]:null},setItem:function(k,v){store[k]=String(v)},removeItem:function(k){delete store[k]}}};var sandbox={window:w,globalThis:w,console:console,JSON:JSON,Math:Math,Number:Number,String:String,Array:Array,Object:Object,Date:Date,setTimeout:setTimeout};vm.runInNewContext(source,sandbox,{filename:'electric-residential-wire-takeoff.js'});return w.BrunoResidentialWireTakeoff}
function live(){return global.BrunoResidentialLive.calculate({squareFeet:1000,bedrooms:2,livingRooms:1,diningRooms:1,offices:0,bathrooms:1,powderRooms:0,kitchens:1,laundryAreas:1,garageBays:1,outdoorGfci:1,qualifyingWallSegmentsFt:'',generalCircuitAmps:20,receptaclesPerGeneralCircuit:5,overrides:{generalReceptacles:10,bathroomReceptacles:1,kitchenReceptacles:6,outdoorReceptacles:1,lights:6,switches:6}})}
test('detailed wire takeoff exposes per-scope and cable totals',function(){var M=module(),t=M.calculate(live(),{mode:'detailed',wastePct:10,quickFtPerSqFt:3});is(t.mode,'detailed');is(t.rows.length,6);is(t.cableTotals.length,1);is(t.cableTotals[0].cable,'12/2 NM-B with ground');is(t.totalFt,714);ok(t.basis.indexOf('NOT an NEC minimum')>=0,'estimating disclaimer missing')});
test('detailed waste allowance changes purchase footage without changing raw routing basis',function(){var M=module(),a=M.calculate(live(),{mode:'detailed',wastePct:0,quickFtPerSqFt:3}),b=M.calculate(live(),{mode:'detailed',wastePct:20,quickFtPerSqFt:3});is(a.rawTotalFt,b.rawTotalFt);ok(b.totalFt>a.totalFt,'waste allowance did not increase footage')});
test('15A general circuits split 14/2 from 12/2 special-area cable',function(){var M=module(),r=global.BrunoResidentialLive.calculate({squareFeet:900,bedrooms:1,livingRooms:1,diningRooms:0,offices:0,bathrooms:1,powderRooms:0,kitchens:1,laundryAreas:0,garageBays:0,outdoorGfci:0,qualifyingWallSegmentsFt:'',generalCircuitAmps:15,receptaclesPerGeneralCircuit:5,overrides:{generalReceptacles:5,bathroomReceptacles:1,kitchenReceptacles:6,outdoorReceptacles:0,lights:3,switches:3}}),t=M.calculate(r,{mode:'detailed',wastePct:10,quickFtPerSqFt:3}),names=t.cableTotals.map(function(x){return x.cable}).sort().join('|');ok(names.indexOf('14/2 NM-B with ground')>=0,'14/2 total missing');ok(names.indexOf('12/2 NM-B with ground')>=0,'12/2 special-area total missing')});
test('quick mode is separate budget estimate based on editable ft per sqft coefficient',function(){var M=module(),t=M.calculate(live(),{mode:'quick',wastePct:0,quickFtPerSqFt:3.5});is(t.mode,'quick');is(t.rawTotalFt,3500);is(t.totalFt,3500);is(t.cableTotals[0].cable,'Mixed branch-circuit cable');ok(t.basis.indexOf('Budget estimate')>=0&&t.basis.indexOf('NOT an NEC minimum')>=0,'quick mode labeling unsafe')});
test('quick mode never mutates detailed routing result',function(){var M=module(),r=live(),before=JSON.stringify(r),q=M.calculate(r,{mode:'quick',wastePct:15,quickFtPerSqFt:4});is(JSON.stringify(r),before);ok(q.totalFt>r.summary.totalCableFt,'quick test fixture should remain independently larger than detailed result')});
test('invalid wire settings fail closed',function(){var M=module(),bad=[{mode:'bogus',wastePct:10,quickFtPerSqFt:3},{mode:'detailed',wastePct:-1,quickFtPerSqFt:3},{mode:'quick',wastePct:10,quickFtPerSqFt:0}];bad.forEach(function(x){var threw=false;try{M.calculate(live(),x)}catch(e){threw=true}ok(threw,'invalid setting accepted: '+JSON.stringify(x))})});
test('wire takeoff module contains archive metadata persistence path',function(){ok(source.indexOf('residentialLiveActive.wireTakeoff')>=0,'active snapshot wire metadata missing');ok(source.indexOf("lib[i].wireTakeoff")>=0,'archive wire metadata missing');ok(source.indexOf('data-rl-load')>=0,'archive load settings restore hook missing')});
global.BRUNO_TEST_RESULTS=out;
})();