'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
var src=fs.readFileSync(path.join(__dirname,'..','electric-residential-history-job-scope.js'),'utf8');
function env(job,legacy){var store={'bruno-electric-v1':JSON.stringify(job||{})};if(legacy!==undefined)store['bruno-residential-live-library-v1']=typeof legacy==='string'?legacy:JSON.stringify(legacy);var ls={getItem:function(k){return Object.prototype.hasOwnProperty.call(store,k)?store[k]:null},setItem:function(k,v){store[k]=String(v)},removeItem:function(k){delete store[k]}};var w={localStorage:ls,BrunoResidentialPricing:{priceRows:function(rows){return{rows:(rows||[]).length}}},dispatchEvent:function(){},CustomEvent:function(n){this.type=n}};var sb={window:w,globalThis:w,console:console,Date:Date,JSON:JSON,Math:Math,String:String,Array:Array,Object:Object};vm.runInNewContext(src,sb,{filename:'electric-residential-history-job-scope.js'});return{w:w,store:store,H:w.BrunoResidentialLiveHistory}}
function snap(name){return{name:name,inputs:{squareFeet:1000},bom:[{item:'12/2',qty:100,unit:'FT'}],summary:{totalCableFt:100}}}
test('job-owned Residential archive saves inside bruno-electric-v1',function(){var e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},[]);var s=e.H.save(snap('A'));var j=JSON.parse(e.store['bruno-electric-v1']);is(j.residentialLiveArchive.length,1);is(j.residentialLiveArchive[0].id,s.id);is(e.H.list().length,1)});
test('Job A archive does not leak after replacing active job with Job B',function(){var e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},[{id:'legacy-a',name:'Legacy A',bom:[]}]);e.H.save(snap('Job A'));var a=JSON.parse(e.store['bruno-electric-v1']);is(a.residentialLiveArchive.length,1);e.w.localStorage.setItem('bruno-electric-v1',JSON.stringify({quote:{jobNumber:'B'},catalog:[],materialsUsed:[],materialsUnresolved:[]}));is(e.H.list().length,0)});
test('legacy global archive remains non-authoritative and preserved raw',function(){var legacy=[{id:'old-a',name:'Old A',bom:[]}],e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},legacy);is(e.H.list().length,0);is(e.H.legacyList().length,1);is(JSON.parse(e.store['bruno-residential-live-library-v1']).length,1)});
test('explicit legacy recovery copies into current job without deleting legacy source',function(){var legacy=[{id:'old-a',name:'Old A',inputs:{squareFeet:900},bom:[]}],e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},legacy),r=e.H.importLegacyToCurrent(['old-a']),j=JSON.parse(e.store['bruno-electric-v1']);is(r.imported,1);is(j.residentialLiveArchive.length,1);is(j.residentialLiveArchive[0].legacyOriginalId,'old-a');is(JSON.parse(e.store['bruno-residential-live-library-v1']).length,1)});
test('legacy preloaded closure writes are virtualized into active Job archive',function(){var e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},[{id:'raw-preserved',name:'Raw',bom:[]}]);e.w.localStorage.setItem('bruno-residential-live-library-v1',JSON.stringify([{id:'virtual-row',name:'Virtual',bom:[]}]));var j=JSON.parse(e.store['bruno-electric-v1']);is(j.residentialLiveArchive[0].id,'virtual-row');is(JSON.parse(e.store['bruno-residential-live-library-v1'])[0].id,'raw-preserved')});
test('job JSON export/import naturally carries Residential archive',function(){var e=env({catalog:[],materialsUsed:[],materialsUnresolved:[]},[]);e.H.save(snap('Exported'));var exported=e.store['bruno-electric-v1'];e.w.localStorage.setItem('bruno-electric-v1',JSON.stringify({catalog:[],materialsUsed:[],materialsUnresolved:[]}));is(e.H.list().length,0);e.w.localStorage.setItem('bruno-electric-v1',exported);is(e.H.list().length,1);is(e.H.list()[0].name,'Exported')});
test('malformed legacy archive cannot erase current job archive',function(){var e=env({catalog:[],materialsUsed:[],materialsUnresolved:[],residentialLiveArchive:[{id:'keep',name:'Keep',bom:[]}]},'{bad');is(e.H.list().length,1);is(e.H.list()[0].id,'keep');is(e.H.legacyList().length,0)});
global.BRUNO_TEST_RESULTS=out;
})();
