'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function boot(state){var source=fs.readFileSync(path.join(__dirname,'..','electric-residential-live-workspace.js'),'utf8'),listeners={},chipValue={textContent:''},chipWrap={style:{},title:'',attrs:{},setAttribute:function(k,v){this.attrs[k]=String(v)}},bar={appendChild:function(){}};var document={readyState:'complete',querySelector:function(sel){return sel==='.live-totals'?bar:null},getElementById:function(id){if(id==='chip-res-live-wrap')return chipWrap;if(id==='chip-res-live')return chipValue;return null},createElement:function(){return chipWrap},addEventListener:function(name,fn){listeners[name]=fn}};var sandbox={window:null,document:document,console:console,localStorage:{getItem:function(k){return k==='bruno-electric-v1'?JSON.stringify(state):null}},setTimeout:function(fn){fn();return 1},clearTimeout:function(){}};sandbox.window=sandbox;sandbox.addEventListener=function(name,fn){listeners['window:'+name]=fn};vm.runInNewContext(source,sandbox,{filename:'electric-residential-live-workspace.js'});return{listeners:listeners,chipValue:chipValue,chipWrap:chipWrap,sandbox:sandbox}}
test('Job workspace chip displays applied Residential calculation provenance',function(){var x=boot({residentialLiveActive:{id:'calc-1',name:'Saved Plan'},residentialAppliedCalculation:{calculationId:'calc-1',name:'Applied Plan',appliedAt:'2026-09-16T00:00:00Z',sourceVersion:'residential-apply-v1'}});is(x.chipValue.textContent,'Applied Plan');is(x.chipWrap.attrs['data-applied-calculation-id'],'calc-1');is(x.chipWrap.attrs['data-applied-state'],'APPLIED_CURRENT');ok(x.chipWrap.title.indexOf('residential-apply-v1')>=0,'source version missing from provenance tooltip')});
test('Job workspace flags newer saved calculation as not yet applied',function(){var x=boot({residentialLiveActive:{id:'calc-2',name:'Newer Saved'},residentialAppliedCalculation:{calculationId:'calc-1',name:'Applied Plan',appliedAt:'now',sourceVersion:'residential-apply-v1'}});is(x.chipWrap.attrs['data-applied-state'],'SAVED_NEWER_NOT_APPLIED');ok(x.chipWrap.title.indexOf('NOT applied')>=0,'newer saved/not-applied warning missing')});
test('Job workspace hides Residential chip when no calculation is applied',function(){var x=boot({residentialLiveActive:{id:'calc-1',name:'Saved only'}});is(x.chipWrap.style.display,'none')});
test('workspace exposes explicit applied-change refresh hook',function(){var source=fs.readFileSync(path.join(__dirname,'..','electric-residential-live-workspace.js'),'utf8');ok(source.indexOf('bruno:residential-applied')>=0,'applied event hook missing');ok(source.indexOf('notifyAppliedChanged')>=0,'public applied refresh hook missing')});
global.BRUNO_TEST_RESULTS=out;
})();