'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
var asyncTests=global.BRUNO_ASYNC_TESTS||(global.BRUNO_ASYNC_TESTS=[]);
function asyncTest(name,fn){out.total++;var p=Promise.resolve().then(fn).then(function(){out.pass++;out.results.push({name:name,ok:true})},function(e){out.fail++;out.results.push({name:name,ok:false,error:e&&e.message||String(e)})});asyncTests.push(p)}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
function currentCache(source){var m=source.match(/const CACHE = '([^']+)'/);if(!m)throw new Error('CACHE constant missing');return m[1]}
asyncTest('service worker activation deletes only owned stale Bruno Electric caches',function(){var source=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),current=currentCache(source),listeners={},deleted=[],cacheNames=['bruno-electric-v45','bruno-electric-v56','bruno-electric-v57','bruno-electric-v58','bruno-electric-v59','bruno-electric-v60','bruno-electric-v65',current,'bruno-ac-v99','other-pwa-cache'].filter(function(x,i,a){return a.indexOf(x)===i});var sandbox={Promise:Promise,URL:URL,console:console,self:{location:{origin:'https://kot0070.github.io'},clients:{claim:function(){return Promise.resolve()}},skipWaiting:function(){return Promise.resolve()},addEventListener:function(name,handler){listeners[name]=handler}},caches:{keys:function(){return Promise.resolve(cacheNames.slice())},delete:function(name){deleted.push(name);return Promise.resolve(true)},open:function(){return Promise.resolve({addAll:function(){return Promise.resolve()},add:function(){return Promise.resolve()},put:function(){return Promise.resolve()}})},match:function(){return Promise.resolve(null)}},fetch:function(){return Promise.reject(new Error('network disabled'))}};vm.runInNewContext(source,sandbox,{filename:'sw.js'});var waited;listeners.activate({waitUntil:function(p){waited=p}});return waited.then(function(){deleted.sort();var expected=cacheNames.filter(function(x){return /^bruno-electric-v\d+$/.test(x)&&x!==current}).sort();is(deleted.join('|'),expected.join('|'));var kept=cacheNames.filter(function(x){return deleted.indexOf(x)<0}).sort();is(kept.join('|'),['bruno-ac-v99',current,'other-pwa-cache'].sort().join('|'))})});
asyncTest('service worker current core shell includes workflow and Electrical Tasks solver runtimes',function(){var source=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),current=currentCache(source);if(!/^bruno-electric-v\d+$/.test(current))throw new Error('invalid Bruno Electric cache name');['electric-dispatch-journal-v2.js','electric-catalog-cost-semantics.js','electric-pricing-margins-semantics.js','electric-job-material-cost-semantics.js','electric-job-summary-semantics.js','electric-pricing-domain-guard.js','electric-quote-lifecycle.js','electric-fixed-price-invoice.js','electric-catalog-job-ux-semantics.js','electric-custom-materials.js','electric-electrical-tasks.js','electric-electrical-task-engine.js','electric-raceway-engine.js','electric-grounding-reference.js','electric-grounding-engine.js','electric-electrical-task-advanced.js','electric-electrical-task-solver.js','electric-electrical-task-material-takeoff.js','electric-electrical-task-archive.js','electrical-tasks-ui.js','electrical-tasks-stage2-ui.js','electrical-tasks-stage3-ui.js','electrical-tasks-stage4-ui.js','electrical-tasks-stage5-ui.js','electrical-tasks-stage6-ui.js','electrical-tasks-stage7-ui.js','electrical-tasks-stage8-ui.js','electrical-project-calculator-ui.js','electric-residential-live.js','electrical-residential-live-ui.js','electric-residential-live-history.js','electric-residential-history-job-scope.js','electric-residential-wire-takeoff.js','electric-residential-apply-job.js','electric-residential-save-archive-ux.js','electric-residential-catalog-bridge.js','electrical-tools-shell.js'].forEach(function(name){if(source.indexOf("'./"+name+"'")<0)throw new Error(name+' missing from core shell')});if(source.indexOf("'./electric-project-mode.js'")>=0)throw new Error('obsolete global project mode still cached');if(source.indexOf(".catch(() => null)")<0)throw new Error('optional cache failure isolation missing')});
global.BRUNO_TEST_RESULTS=out;
})();
