'use strict';
(function(){
var fs=require('fs'),path=require('path'),vm=require('vm');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
var asyncTests=global.BRUNO_ASYNC_TESTS||(global.BRUNO_ASYNC_TESTS=[]);
function asyncTest(name,fn){out.total++;var p=Promise.resolve().then(fn).then(function(){out.pass++;out.results.push({name:name,ok:true})},function(e){out.fail++;out.results.push({name:name,ok:false,error:e&&e.message||String(e)})});asyncTests.push(p)}
function is(a,b){if(a!==b)throw new Error('expected '+JSON.stringify(b)+', got '+JSON.stringify(a))}
asyncTest('service worker activation deletes only owned stale Bruno Electric caches',function(){var source=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8'),listeners={},deleted=[],cacheNames=['bruno-electric-v38','bruno-electric-v39','bruno-electric-v40','bruno-ac-v99','other-pwa-cache'];var sandbox={Promise:Promise,URL:URL,console:console,self:{location:{origin:'https://kot0070.github.io'},clients:{claim:function(){return Promise.resolve()}},skipWaiting:function(){return Promise.resolve()},addEventListener:function(name,handler){listeners[name]=handler}},caches:{keys:function(){return Promise.resolve(cacheNames.slice())},delete:function(name){deleted.push(name);return Promise.resolve(true)},open:function(){return Promise.resolve({addAll:function(){return Promise.resolve()},add:function(){return Promise.resolve()},put:function(){return Promise.resolve()}})},match:function(){return Promise.resolve(null)}},fetch:function(){return Promise.reject(new Error('network disabled'))}};vm.runInNewContext(source,sandbox,{filename:'sw.js'});var waited;listeners.activate({waitUntil:function(p){waited=p}});return waited.then(function(){deleted.sort();is(deleted.join('|'),'bruno-electric-v38|bruno-electric-v39');var kept=cacheNames.filter(function(x){return deleted.indexOf(x)<0}).sort();is(kept.join('|'),['bruno-ac-v99','bruno-electric-v40','other-pwa-cache'].sort().join('|'))})});
asyncTest('service worker core shell includes project-first calculator and journal',function(){var source=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');['electric-dispatch-journal-v2.js','electrical-project-calculator-ui.js','electric-residential-live.js','electrical-residential-live-ui.js','electric-residential-live-history.js','electrical-tools-shell.js'].forEach(function(name){if(source.indexOf("'./"+name+"'")<0)throw new Error(name+' missing from core shell')});if(source.indexOf("bruno-electric-v40")<0)throw new Error('v40 cache missing');if(source.indexOf("'./electric-project-mode.js'")>=0)throw new Error('obsolete global project mode still cached')});
global.BRUNO_TEST_RESULTS=out;
})();