'use strict';
(function(){
var fs=require('fs'),path=require('path');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function src(name){return fs.readFileSync(path.join(__dirname,'..',name),'utf8')}
var reg=src('sw-register.js'),sw=src('sw.js'),tools=src('electrical-tools.html'),custom=src('electric-custom-materials.js'),quote=src('electric-quote-lifecycle.js'),fixed=src('electric-fixed-price-invoice.js'),historyScope=src('electric-residential-history-job-scope.js'),apply=src('electric-residential-apply-job.js'),saveUx=src('electric-residential-save-archive-ux.js'),summary=src('electric-job-summary-semantics.js'),catUx=src('electric-catalog-job-ux-semantics.js');
test('final bootstrap loads every workflow and v51 corrective runtime on Job app',function(){['electric-job-summary-semantics.js','electric-quote-lifecycle.js','electric-fixed-price-invoice.js','electric-catalog-job-ux-semantics.js','electric-custom-materials.js','electric-residential-history-job-scope.js','electric-residential-wire-takeoff.js','electric-residential-apply-job.js','electric-residential-save-archive-ux.js'].forEach(function(n){ok(reg.indexOf(n)>=0,n+' missing from bootstrap')})});
test('final PWA v51 core shell mirrors required workflow and corrective runtimes',function(){ok(sw.indexOf("bruno-electric-v51")>=0,'v51 missing');['electric-job-summary-semantics.js','electric-quote-lifecycle.js','electric-fixed-price-invoice.js','electric-catalog-job-ux-semantics.js','electric-custom-materials.js','electric-residential-history-job-scope.js','electric-residential-wire-takeoff.js','electric-residential-apply-job.js','electric-residential-save-archive-ux.js'].forEach(function(n){ok(sw.indexOf("'./"+n+"'")>=0,n+' missing from PWA shell')})});
test('Electrical Tools loads job-scope history before Residential Live UI closure capture',function(){var scope=tools.indexOf('./electric-residential-history-job-scope.js'),ui=tools.indexOf('./electrical-residential-live-ui.js'),legacy=tools.indexOf('./electric-residential-live-history.js');ok(legacy>=0,'legacy compatibility history loader missing');ok(scope>legacy,'job scope must load after legacy API definition');ok(scope<ui,'job scope must load before Residential Live UI captures history API')});
test('Custom Quote and Residential archive authority persist inside active Job state',function(){ok(custom.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'Custom Job key missing');ok(quote.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'Quote Job key missing');ok(historyScope.indexOf("ARCHIVE_FIELD='residentialLiveArchive'")>=0,'job-owned Residential archive field missing');ok(custom.indexOf("CUSTOM_KEY='bruno-electric-custom-materials-v1'")<0,'global Custom registry returned')});
test('Save Apply Quote Invoice boundaries are separately represented',function(){ok(saveUx.indexOf('Save Calculation')>=0,'Save boundary missing');ok(apply.indexOf('applyActive')>=0,'Apply boundary missing');ok(quote.indexOf('APPROVED_QUOTE_SNAPSHOT')>=0,'Approved Quote snapshot boundary missing');ok(fixed.indexOf('invoiceBasis()')>=0,'fixed invoice approved-snapshot boundary missing');ok(fixed.indexOf('Print Fixed-Price Invoice')>=0,'fixed invoice action missing')});
test('fixed-price Invoice never reads moving live quote DOM totals',function(){ok(fixed.indexOf("getElementById('q-total')")<0,'fixed Invoice reads live q-total');ok(fixed.indexOf("getElementById('chip-quote')")<0,'fixed Invoice reads live quote chip');ok(fixed.indexOf('APPROVED_QUOTE_SNAPSHOT')>=0,'fixed Invoice approved source check missing')});
test('legacy Residential archive is explicitly non-authoritative recovery data',function(){ok(historyScope.indexOf("LEGACY_LIB_KEY='bruno-residential-live-library-v1'")>=0,'legacy archive reference missing');ok(historyScope.indexOf('legacyList')>=0,'legacy recovery read missing');ok(historyScope.indexOf('importLegacyToCurrent')>=0,'explicit legacy recovery import missing');ok(historyScope.indexOf('residentialLiveArchive')>=0,'job archive authority missing')});
test('unresolved contractor cost remains first-class through Job Quote and fixed Invoice layers',function(){ok(summary.indexOf('INCOMPLETE MATERIAL COST')>=0,'Job unresolved disclosure missing');ok(quote.indexOf('unresolvedMaterialCountAtApproval')>=0,'Quote unresolved snapshot missing');ok(fixed.indexOf('unresolvedMaterialCountAtApproval')>=0,'fixed Invoice unresolved snapshot disclosure missing');ok(custom.indexOf("costState='UNRESOLVED'")>=0,'Custom unresolved state missing')});
test('Catalog and Job Materials UX exposes definition-vs-snapshot semantics',function(){ok(catUx.indexOf('Catalog = reusable definition for this Job')>=0,'Catalog definition semantics missing');ok(catUx.indexOf('Job Materials = historical calculation snapshots')>=0,'Job snapshot semantics missing')});
test('newly introduced workflow controls retain phone-responsive contracts',function(){ok(custom.indexOf('@media(max-width:767.98px)')>=0,'Custom phone CSS missing');ok(catUx.indexOf('@media(max-width:767.98px)')>=0,'Catalog/Job badge phone CSS missing');ok(quote.indexOf('grid grid-2')>=0,'Quote lifecycle responsive grid integration missing');ok(fixed.indexOf('display:flex')>=0,'fixed Invoice layout missing')});
global.BRUNO_TEST_RESULTS=out;
})();
