'use strict';
(function(){
var fs=require('fs'),path=require('path');
var out=global.BRUNO_TEST_RESULTS||{total:0,pass:0,fail:0,results:[]};
function test(name,fn){out.total++;try{fn();out.pass++;out.results.push({name:name,ok:true})}catch(e){out.fail++;out.results.push({name:name,ok:false,error:e.message})}}
function ok(v,m){if(!v)throw new Error(m||'assertion failed')}
function src(name){return fs.readFileSync(path.join(__dirname,'..',name),'utf8')}
var reg=src('sw-register.js'),sw=src('sw.js'),tools=src('electrical-tools.html'),custom=src('electric-custom-materials.js'),guard=src('electric-pricing-domain-guard.js'),quote=src('electric-quote-lifecycle.js'),fixed=src('electric-fixed-price-invoice.js'),historyScope=src('electric-residential-history-job-scope.js'),live=src('electric-residential-live.js'),calc=src('electric-calculators.js'),apply=src('electric-residential-apply-job.js'),saveUx=src('electric-residential-save-archive-ux.js'),summary=src('electric-job-summary-semantics.js'),catUx=src('electric-catalog-job-ux-semantics.js'),taskCore=src('electric-electrical-tasks.js'),taskEngine=src('electric-electrical-task-engine.js'),raceway=src('electric-raceway-engine.js'),grounding=src('electric-grounding-engine.js'),taskArchive=src('electric-electrical-task-archive.js'),taskAdvanced=src('electric-electrical-task-advanced.js');
test('final bootstrap loads workflow corrective and Electrical Tasks Stage 7A runtimes',function(){['electric-job-summary-semantics.js','electric-pricing-domain-guard.js','electric-quote-lifecycle.js','electric-fixed-price-invoice.js','electric-catalog-job-ux-semantics.js','electric-custom-materials.js','electric-residential-history-job-scope.js','electric-residential-wire-takeoff.js','electric-residential-apply-job.js','electric-residential-save-archive-ux.js','electric-electrical-tasks.js','electric-electrical-task-engine.js','electric-raceway-engine.js','electric-grounding-reference.js','electric-grounding-engine.js','electric-electrical-task-advanced.js','electric-electrical-task-material-takeoff.js','electric-electrical-task-archive.js','electrical-tasks-ui.js','electrical-tasks-stage2-ui.js','electrical-tasks-stage3-ui.js','electrical-tasks-stage4-ui.js','electrical-tasks-stage5-ui.js','electrical-tasks-stage6-ui.js','electrical-tasks-stage7-ui.js'].forEach(function(n){ok(reg.indexOf(n)>=0,n+' missing from bootstrap')})});
test('final PWA v59 core shell mirrors workflow and Electrical Tasks Stage 7A runtimes',function(){ok(sw.indexOf("bruno-electric-v59")>=0,'v59 missing');['electric-pricing-domain-guard.js','electric-job-summary-semantics.js','electric-quote-lifecycle.js','electric-fixed-price-invoice.js','electric-catalog-job-ux-semantics.js','electric-custom-materials.js','electric-residential-history-job-scope.js','electric-residential-wire-takeoff.js','electric-residential-apply-job.js','electric-residential-save-archive-ux.js','electric-electrical-tasks.js','electric-electrical-task-engine.js','electric-raceway-engine.js','electric-grounding-reference.js','electric-grounding-engine.js','electric-electrical-task-advanced.js','electric-electrical-task-material-takeoff.js','electric-electrical-task-archive.js','electrical-tasks-ui.js','electrical-tasks-stage2-ui.js','electrical-tasks-stage3-ui.js','electrical-tasks-stage4-ui.js','electrical-tasks-stage5-ui.js','electrical-tasks-stage6-ui.js','electrical-tasks-stage7-ui.js'].forEach(function(n){ok(sw.indexOf("'./"+n+"'")>=0,n+' missing from PWA shell')})});
test('pricing bootstrap is ordered guard then Quote lifecycle then fixed Invoice',function(){ok(reg.indexOf('s.onload=loadQuoteLifecycle')>=0,'domain guard does not chain Quote lifecycle');ok(reg.indexOf('s.onload=loadFixedPriceInvoice')>=0,'Quote lifecycle does not chain fixed Invoice');var start=reg.indexOf('function loadAppNavigation'),end=reg.indexOf('\n  prepareStrictMarginsRuntime();',start),app=reg.slice(start,end);ok(app.indexOf('loadPricingDomainGuard()')>=0,'domain guard bootstrap missing');ok(app.indexOf('loadQuoteLifecycle()')<0,'Quote is still started independently of guard');ok(app.indexOf('loadFixedPriceInvoice()')<0,'fixed Invoice is still started independently of Quote')});
test('Quote approval programmatic path asserts pricing domain guard',function(){ok(quote.indexOf('BrunoPricingDomainGuard')>=0,'Quote does not reference pricing guard');ok(quote.indexOf('assertPricingValid(j)')>=0,'Quote approval does not assert current Job numeric domain')});
test('pricing guard blocks live approval Quote and T&M outputs but not immutable approved fixed Invoice',function(){['qa-approve','btn-print-tm','btn-print-tm-2','btn-print-quote'].forEach(function(id){ok(guard.indexOf("'"+id+"'")>=0,id+' not guarded')});var controls=guard.slice(guard.indexOf('function controls()'),guard.indexOf('function render()'));ok(controls.indexOf('qa-print-fixed')<0,'immutable approved fixed Invoice incorrectly depends on later live Job state')});
test('math corrective K-method is resistance-only and Residential 120.13 floor is explicit',function(){ok(calc.indexOf("method:'RESISTANCE_ONLY_K'")>=0,'resistance-only voltage-drop contract missing');ok(calc.indexOf('amps * distance / cmil')>=0,'K-method corrective formula missing');ok(live.indexOf('branchCircuitGeneralVAperFt2')>=0,'branch circuit 3 VA/ft² input missing');ok(live.indexOf("reference:'NEC 2026 120.13'")>=0,'120.13 minimum provenance missing');ok(live.indexOf('Math.max(codeGeneralCircuits,groupingGeneralCircuits)')>=0,'code floor cannot dominate design grouping')});
test('Electrical Tools loads job-scope history before Residential Live UI closure capture',function(){var scope=tools.indexOf('./electric-residential-history-job-scope.js'),ui=tools.indexOf('./electrical-residential-live-ui.js'),legacy=tools.indexOf('./electric-residential-live-history.js');ok(legacy>=0,'legacy compatibility history loader missing');ok(scope>legacy,'job scope must load after legacy API definition');ok(scope<ui,'job scope must load before Residential Live UI captures history API')});
test('Custom Quote Residential archive and Electrical Tasks authority persist inside active Job state',function(){ok(custom.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'Custom Job key missing');ok(quote.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'Quote Job key missing');ok(historyScope.indexOf("ARCHIVE_FIELD='residentialLiveArchive'")>=0,'job-owned Residential archive field missing');ok(taskCore.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'Electrical Tasks Job key missing');ok(taskCore.indexOf("FIELD='electricalTasks'")>=0,'Electrical Tasks job-scoped field missing');ok(taskArchive.indexOf("JOB_KEY='bruno-electric-v1'")>=0,'task archive not Job-scoped');ok(custom.indexOf("CUSTOM_KEY='bruno-electric-custom-materials-v1'")<0,'global Custom registry returned')});
test('Electrical Task feeder raceway grounding and Stage 7A branch adapter expose fail-closed contracts',function(){ok(taskEngine.indexOf("NO SUPPORTED CONFIGURATION")>=0,'task fail-closed output missing');ok(taskEngine.indexOf('FEWEST_PARALLEL_SETS_THEN_MINIMUM_TOTAL_CIRCULAR_MIL_AREA')>=0,'explicit candidate ranking missing');ok(taskEngine.indexOf("method:'RESISTANCE_ONLY_K'")>=0,'task voltage-drop method contract missing');ok(raceway.indexOf("NO SUPPORTED CONFIGURATION")>=0,'raceway fail-closed output missing');ok(raceway.indexOf('PHASE_CONDUCTORS_ONLY_STAGE_3')>=0,'Stage 3 scope disclosure missing');ok(grounding.indexOf("neutralMode==='UNRESOLVED'")>=0,'neutral fail-closed contract missing');ok(grounding.indexOf('GEC sizing remains separate verification required')>=0,'GEC separation missing');ok(taskAdvanced.indexOf('Branch-specific load, OCPD, equipment and special-occupancy rules are not inferred')>=0,'Branch scope boundary missing')});
test('Save Apply Update Quote Invoice boundaries are separately represented',function(){ok(saveUx.indexOf('Save Calculation')>=0,'Save boundary missing');ok(apply.indexOf('applyActive')>=0,'Apply boundary missing');ok(taskArchive.indexOf('function update(plan)')>=0,'Task Update Job boundary missing');ok(quote.indexOf('APPROVED_QUOTE_SNAPSHOT')>=0,'Approved Quote snapshot boundary missing');ok(fixed.indexOf('invoiceBasis()')>=0,'fixed invoice approved-snapshot boundary missing');ok(fixed.indexOf('Print Fixed-Price Invoice')>=0,'fixed Invoice action missing')});
test('fixed-price Invoice never reads moving live quote DOM totals',function(){ok(fixed.indexOf("getElementById('q-total')")<0,'fixed Invoice reads live q-total');ok(fixed.indexOf("getElementById('chip-quote')")<0,'fixed Invoice reads live quote chip');ok(fixed.indexOf('APPROVED_QUOTE_SNAPSHOT')>=0,'fixed Invoice approved source check missing')});
test('legacy Residential archive is explicitly non-authoritative recovery data',function(){ok(historyScope.indexOf("LEGACY_LIB_KEY='bruno-residential-live-library-v1'")>=0,'legacy archive reference missing');ok(historyScope.indexOf('legacyList')>=0,'legacy recovery read missing');ok(historyScope.indexOf('importLegacyToCurrent')>=0,'explicit legacy recovery import missing');ok(historyScope.indexOf('residentialLiveArchive')>=0,'job archive authority missing')});
test('unresolved contractor cost remains first-class through Job Quote and fixed Invoice layers',function(){ok(summary.indexOf('INCOMPLETE MATERIAL COST')>=0,'Job unresolved disclosure missing');ok(quote.indexOf('unresolvedMaterialCountAtApproval')>=0,'Quote unresolved snapshot missing');ok(fixed.indexOf('unresolvedMaterialCountAtApproval')>=0,'fixed Invoice unresolved snapshot disclosure missing');ok(custom.indexOf("costState='UNRESOLVED'")>=0,'Custom unresolved state missing')});
test('Catalog and Job Materials UX exposes definition-vs-snapshot semantics',function(){ok(catUx.indexOf('Catalog = reusable definition for this Job')>=0,'Catalog definition semantics missing');ok(catUx.indexOf('Job Materials = historical calculation snapshots')>=0,'Job snapshot semantics missing')});
test('newly introduced workflow controls retain phone-responsive contracts',function(){ok(custom.indexOf('@media(max-width:767.98px)')>=0,'Custom phone CSS missing');ok(catUx.indexOf('@media(max-width:767.98px)')>=0,'Catalog/Job badge phone CSS missing');ok(quote.indexOf('grid grid-2')>=0,'Quote lifecycle responsive grid integration missing');ok(fixed.indexOf('display:flex')>=0,'fixed Invoice layout missing')});
global.BRUNO_TEST_RESULTS=out;
})();