from pathlib import Path

# electrical-tools-ui.js
p=Path('electrical-tools-ui.js'); s=p.read_text()
s=s.replace('<div class="field"><label>Raceway</label><select id="c-r"><option>EMT</option><option value="PVC40">PVC40</option></select></div><div class="field"><label>Trade size</label><select id="c-ts">${selectOpts([\'1/2\',\'3/4\',\'1\',\'1-1/4\',\'1-1/2\',\'2\'],\'3/4\')}</select></div>', '<div class="field"><label>Raceway</label><select id="c-r">${selectOpts(Object.keys(R.RACEWAY_AREA),\'EMT\')}</select></div><div class="field"><label>Trade size</label><select id="c-ts">${selectOpts(Object.keys(R.RACEWAY_AREA.EMT),\'3/4\')}</select></div>')
s=s.replace("function addConductor(size,qty){var d=document.createElement('div');d.className='fields c-row';d.style.marginBottom='8px';d.innerHTML='<div class=\"field\"><label>Size</label><select class=\"c-size\">'+selectOpts(['14','12','10','8','6','4','3','2','1','1/0','2/0','3/0','4/0'],size||'12')+'</select></div><div class=\"field\"><label>Qty</label><input class=\"c-qty\" type=\"number\" min=\"1\" value=\"'+(qty||1)+'\"></div>';f('c-rows').appendChild(d)}", "function addConductor(size,qty){var d=document.createElement('div');d.className='fields c-row';d.style.marginBottom='8px';d.innerHTML='<div class=\"field\"><label>Size</label><select class=\"c-size\">'+selectOpts(Object.keys(R.THHN_AREA),size||'12')+'</select></div><div class=\"field\"><label>Qty</label><input class=\"c-qty\" type=\"number\" min=\"1\" value=\"'+(qty||1)+'\"></div>';f('c-rows').appendChild(d)}")
s=s.replace("addConductor('12',3);f('c-add').onclick=function(){addConductor('12',1)};", "addConductor('12',3);f('c-add').onclick=function(){addConductor('12',1)};f('c-r').onchange=function(){var sizes=Object.keys(R.RACEWAY_AREA[this.value]||{}),sel=f('c-ts');sel.innerHTML=selectOpts(sizes,sizes.indexOf('3/4')>=0?'3/4':sizes[0])};")
s=s.replace("function renderResult(outId,r){var o=f(outId);var h='<h3>Calculation path · <span class=\"'+(r.status==='PASS'?'pass':r.status==='FAIL'?'fail':'')+'\">'+esc(r.status)+'</span></h3><table class=\"steps\"><thead><tr><th>Step</th><th>Value</th><th>Status</th></tr></thead><tbody>';", "function renderResult(outId,r){var o=f(outId);var verdict='';if(r.module==='voltageDrop'&&r.result){var ok=r.status==='PASS';verdict='<div class=\"'+(ok?'pass':'warn')+'\" style=\"padding:10px 12px;border-radius:8px;margin:0 0 12px;font-weight:800\">'+esc(r.status)+' · '+esc(r.result.percentDropped)+'% drop '+(ok?'≤':'&gt;')+' '+esc(r.result.targetPct)+'% target · '+esc(r.result.voltageAtLoad)+' V at load</div>'}var h=verdict+'<h3>Calculation path · <span class=\"'+(r.status==='PASS'?'pass':r.status==='FAIL'?'fail':'')+'\">'+esc(r.status)+'</span></h3><table class=\"steps\"><thead><tr><th>Step</th><th>Value</th><th>Status</th></tr></thead><tbody>';")
p.write_text(s)

# motor HP/W helper UI
p=Path('electrical-phase3-ui.js'); s=p.read_text()
needle='<section class="tool" id="tool-mo3"><div class="grid"><div class="card"><h2>Single Motor Circuit</h2><p>Supported scope: common AC motor, continuous duty. Use Article 430 table FLC for conductor/SCGF sizing and nameplate current for overload.</p><div class="fields">'
replacement='<section class="tool" id="tool-mo3"><div class="grid"><div class="card"><h2>Single Motor Circuit</h2><p>Supported scope: common AC motor, continuous duty. Article 430 table FLC remains authoritative for conductor/SCGF sizing. HP/W helper estimates operating/nameplate current only.</p><div class="fields"><div class="field"><label>Power helper</label><select id="mo-punit"><option value="hp">Horsepower (HP)</option><option value="w">Watts (W)</option></select></div><div class="field"><label>Power value</label><input id="mo-power" type="number" value="5" step="0.01"></div><div class="field"><label>Voltage</label><input id="mo-v" type="number" value="240"></div><div class="field"><label>Phase</label><select id="mo-ph"><option value="1">Single-phase</option><option value="3">Three-phase</option></select></div><div class="field"><label>Power factor</label><input id="mo-pf" type="number" value="0.90" step="0.01"></div><div class="field"><label>Efficiency</label><input id="mo-eff" type="number" value="0.90" step="0.01"></div></div><div class="actions"><button id="mo-estimate">Estimate current from HP/W</button></div><div id="mo-est-note" class="warn" style="display:none;margin:10px 0"></div><div class="fields">'
if needle not in s: raise SystemExit('motor needle missing')
s=s.replace(needle,replacement,1)
marker="f('mo-run').onclick=function(){safe('mo-out',function(){var r=E.motor({tableFlcA:n('mo-flc'),nameplateA:n('mo-np'),deviceType:raw('mo-dev'),serviceFactor115OrTempRise40:raw('mo-sf')==='1',egcMaterial:raw('mo-g')});"
helper="f('mo-estimate').onclick=function(){safe('mo-out',function(){var power=n('mo-power'),unit=raw('mo-punit'),v=n('mo-v'),ph=raw('mo-ph'),pf=n('mo-pf'),eff=n('mo-eff');if(power<=0||v<=0||pf<=0||pf>1||eff<=0||eff>1)throw new Error('Power, voltage, PF and efficiency must be valid; PF/efficiency cannot exceed 1');var watts=unit==='hp'?power*746:power;var amps=watts/((ph==='3'?Math.sqrt(3):1)*v*pf*eff);f('mo-np').value=(Math.round(amps*100)/100).toFixed(2);var note=f('mo-est-note');note.style.display='block';note.textContent=(unit==='hp'?power+' HP ≈ '+Math.round(watts)+' W':Math.round(watts)+' W')+' → estimated '+(Math.round(amps*100)/100).toFixed(2)+' A. Verify NEC Article 430 table FLC separately for conductor and SC/GF sizing.';return{module:'motorPowerHelper',status:'INFO',warnings:[]}})};\n"+marker
if marker not in s: raise SystemExit('motor marker missing')
s=s.replace(marker,helper,1)
p.write_text(s)

# bump visible/runtime generation
for name,old,new in [('sw-register.js',"BUILD_VERSION='1.18'","BUILD_VERSION='1.19'"),('electric-app-version.js',"var VERSION='v1.18'","var VERSION='v1.19'"),('index.html','./sw-register.js?v=1.18','./sw-register.js?v=1.19')]:
    p=Path(name); x=p.read_text()
    if old not in x: raise SystemExit(name+' version target missing')
    p.write_text(x.replace(old,new))
for name in ['tests/customer-documents.test.js','tests/e2e/runtime-generation-stability.spec.js']:
    p=Path(name); x=p.read_text().replace('v1.18','v1.19').replace("BUILD_VERSION='1.18'","BUILD_VERSION='1.19'"); p.write_text(x)
